//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVP.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations_tr {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations_tr() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MVP.Resources.Translations.tr", typeof(Translations_tr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string contributions_title {
            get {
                return ResourceManager.GetString("contributions_title", resourceCulture);
            }
        }
        
        internal static string search_placeholder {
            get {
                return ResourceManager.GetString("search_placeholder", resourceCulture);
            }
        }
        
        internal static string retry {
            get {
                return ResourceManager.GetString("retry", resourceCulture);
            }
        }
        
        internal static string profile_title {
            get {
                return ResourceManager.GetString("profile_title", resourceCulture);
            }
        }
        
        internal static string setting_contributionfromurl_title {
            get {
                return ResourceManager.GetString("setting_contributionfromurl_title", resourceCulture);
            }
        }
        
        internal static string setting_contributionfromurl_description {
            get {
                return ResourceManager.GetString("setting_contributionfromurl_description", resourceCulture);
            }
        }
        
        internal static string setting_apptheme_title {
            get {
                return ResourceManager.GetString("setting_apptheme_title", resourceCulture);
            }
        }
        
        internal static string setting_apptheme_description {
            get {
                return ResourceManager.GetString("setting_apptheme_description", resourceCulture);
            }
        }
        
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        internal static string tabs_activities {
            get {
                return ResourceManager.GetString("tabs_activities", resourceCulture);
            }
        }
        
        internal static string tabs_statistics {
            get {
                return ResourceManager.GetString("tabs_statistics", resourceCulture);
            }
        }
        
        internal static string tabs_badges {
            get {
                return ResourceManager.GetString("tabs_badges", resourceCulture);
            }
        }
        
        internal static string tabs_settings {
            get {
                return ResourceManager.GetString("tabs_settings", resourceCulture);
            }
        }
        
        internal static string contributionform_title_add {
            get {
                return ResourceManager.GetString("contributionform_title_add", resourceCulture);
            }
        }
        
        internal static string contributionform_title_edit {
            get {
                return ResourceManager.GetString("contributionform_title_edit", resourceCulture);
            }
        }
        
        internal static string languagepicker_title {
            get {
                return ResourceManager.GetString("languagepicker_title", resourceCulture);
            }
        }
        
        internal static string contributiondetails_title {
            get {
                return ResourceManager.GetString("contributiondetails_title", resourceCulture);
            }
        }
        
        internal static string field_activity_type {
            get {
                return ResourceManager.GetString("field_activity_type", resourceCulture);
            }
        }
        
        internal static string field_url {
            get {
                return ResourceManager.GetString("field_url", resourceCulture);
            }
        }
        
        internal static string field_title {
            get {
                return ResourceManager.GetString("field_title", resourceCulture);
            }
        }
        
        internal static string field_primary_contribution_area {
            get {
                return ResourceManager.GetString("field_primary_contribution_area", resourceCulture);
            }
        }
        
        internal static string field_additional_contribution_areas {
            get {
                return ResourceManager.GetString("field_additional_contribution_areas", resourceCulture);
            }
        }
        
        internal static string field_activity_date {
            get {
                return ResourceManager.GetString("field_activity_date", resourceCulture);
            }
        }
        
        internal static string field_description {
            get {
                return ResourceManager.GetString("field_description", resourceCulture);
            }
        }
        
        internal static string field_visibility {
            get {
                return ResourceManager.GetString("field_visibility", resourceCulture);
            }
        }
        
        internal static string setting_visibility_title {
            get {
                return ResourceManager.GetString("setting_visibility_title", resourceCulture);
            }
        }
        
        internal static string setting_visibility_placeholder {
            get {
                return ResourceManager.GetString("setting_visibility_placeholder", resourceCulture);
            }
        }
        
        internal static string button_delete_contribution {
            get {
                return ResourceManager.GetString("button_delete_contribution", resourceCulture);
            }
        }
        
        internal static string about_title {
            get {
                return ResourceManager.GetString("about_title", resourceCulture);
            }
        }
        
        internal static string about_why_title {
            get {
                return ResourceManager.GetString("about_why_title", resourceCulture);
            }
        }
        
        internal static string about_why_description {
            get {
                return ResourceManager.GetString("about_why_description", resourceCulture);
            }
        }
        
        internal static string about_opensource_title {
            get {
                return ResourceManager.GetString("about_opensource_title", resourceCulture);
            }
        }
        
        internal static string about_opensource_description {
            get {
                return ResourceManager.GetString("about_opensource_description", resourceCulture);
            }
        }
        
        internal static string becomesponsor {
            get {
                return ResourceManager.GetString("becomesponsor", resourceCulture);
            }
        }
        
        internal static string contributionform_timeframememo {
            get {
                return ResourceManager.GetString("contributionform_timeframememo", resourceCulture);
            }
        }
        
        internal static string contributionform_activitytype_placeholder {
            get {
                return ResourceManager.GetString("contributionform_activitytype_placeholder", resourceCulture);
            }
        }
        
        internal static string contributionform_technologyarea_placeholder {
            get {
                return ResourceManager.GetString("contributionform_technologyarea_placeholder", resourceCulture);
            }
        }
        
        internal static string contributionform_additionaltechnologyarea_placeholder {
            get {
                return ResourceManager.GetString("contributionform_additionaltechnologyarea_placeholder", resourceCulture);
            }
        }
        
        internal static string contributionform_visibility_placeholder {
            get {
                return ResourceManager.GetString("contributionform_visibility_placeholder", resourceCulture);
            }
        }
        
        internal static string setting_language_title {
            get {
                return ResourceManager.GetString("setting_language_title", resourceCulture);
            }
        }
        
        internal static string setting_language_description {
            get {
                return ResourceManager.GetString("setting_language_description", resourceCulture);
            }
        }
        
        internal static string themepicker_title {
            get {
                return ResourceManager.GetString("themepicker_title", resourceCulture);
            }
        }
        
        internal static string contributiontypepicker_title {
            get {
                return ResourceManager.GetString("contributiontypepicker_title", resourceCulture);
            }
        }
        
        internal static string contributiontechnologypicker_title {
            get {
                return ResourceManager.GetString("contributiontechnologypicker_title", resourceCulture);
            }
        }
        
        internal static string splash_contributionareas {
            get {
                return ResourceManager.GetString("splash_contributionareas", resourceCulture);
            }
        }
        
        internal static string splash_contributiontypes {
            get {
                return ResourceManager.GetString("splash_contributiontypes", resourceCulture);
            }
        }
        
        internal static string splash_visibilities {
            get {
                return ResourceManager.GetString("splash_visibilities", resourceCulture);
            }
        }
        
        internal static string splash_gettingready {
            get {
                return ResourceManager.GetString("splash_gettingready", resourceCulture);
            }
        }
        
        internal static string theme_systemdefault {
            get {
                return ResourceManager.GetString("theme_systemdefault", resourceCulture);
            }
        }
        
        internal static string theme_light {
            get {
                return ResourceManager.GetString("theme_light", resourceCulture);
            }
        }
        
        internal static string theme_dark {
            get {
                return ResourceManager.GetString("theme_dark", resourceCulture);
            }
        }
        
        internal static string visibility_title {
            get {
                return ResourceManager.GetString("visibility_title", resourceCulture);
            }
        }
        
        internal static string icon_default {
            get {
                return ResourceManager.GetString("icon_default", resourceCulture);
            }
        }
        
        internal static string icon_darkblue {
            get {
                return ResourceManager.GetString("icon_darkblue", resourceCulture);
            }
        }
        
        internal static string icon_black {
            get {
                return ResourceManager.GetString("icon_black", resourceCulture);
            }
        }
        
        internal static string icon_white {
            get {
                return ResourceManager.GetString("icon_white", resourceCulture);
            }
        }
        
        internal static string icon_rainbow {
            get {
                return ResourceManager.GetString("icon_rainbow", resourceCulture);
            }
        }
        
        internal static string setting_appicon_title {
            get {
                return ResourceManager.GetString("setting_appicon_title", resourceCulture);
            }
        }
        
        internal static string setting_appicon_description {
            get {
                return ResourceManager.GetString("setting_appicon_description", resourceCulture);
            }
        }
        
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        internal static string warning_title {
            get {
                return ResourceManager.GetString("warning_title", resourceCulture);
            }
        }
        
        internal static string contributiondetail_deleteconfirmation {
            get {
                return ResourceManager.GetString("contributiondetail_deleteconfirmation", resourceCulture);
            }
        }
        
        internal static string error_unexpected {
            get {
                return ResourceManager.GetString("error_unexpected", resourceCulture);
            }
        }
        
        internal static string error_badrequest {
            get {
                return ResourceManager.GetString("error_badrequest", resourceCulture);
            }
        }
        
        internal static string error_servererror {
            get {
                return ResourceManager.GetString("error_servererror", resourceCulture);
            }
        }
        
        internal static string alert_error_unauthorized {
            get {
                return ResourceManager.GetString("alert_error_unauthorized", resourceCulture);
            }
        }
        
        internal static string clipboard_title {
            get {
                return ResourceManager.GetString("clipboard_title", resourceCulture);
            }
        }
        
        internal static string clipboard_description {
            get {
                return ResourceManager.GetString("clipboard_description", resourceCulture);
            }
        }
        
        internal static string contributiondetail_notdeleted {
            get {
                return ResourceManager.GetString("contributiondetail_notdeleted", resourceCulture);
            }
        }
        
        internal static string validation_variablefield {
            get {
                return ResourceManager.GetString("validation_variablefield", resourceCulture);
            }
        }
        
        internal static string warning_title_activitylocked {
            get {
                return ResourceManager.GetString("warning_title_activitylocked", resourceCulture);
            }
        }
        
        internal static string warning_description_activitylocked {
            get {
                return ResourceManager.GetString("warning_description_activitylocked", resourceCulture);
            }
        }
        
        internal static string additionaltechnologypicker_title {
            get {
                return ResourceManager.GetString("additionaltechnologypicker_title", resourceCulture);
            }
        }
        
        internal static string error_nomvpaccount {
            get {
                return ResourceManager.GetString("error_nomvpaccount", resourceCulture);
            }
        }
        
        internal static string progress_saving {
            get {
                return ResourceManager.GetString("progress_saving", resourceCulture);
            }
        }
        
        internal static string progress_deleting {
            get {
                return ResourceManager.GetString("progress_deleting", resourceCulture);
            }
        }
        
        internal static string licenses_title {
            get {
                return ResourceManager.GetString("licenses_title", resourceCulture);
            }
        }
        
        internal static string about_licenses_title {
            get {
                return ResourceManager.GetString("about_licenses_title", resourceCulture);
            }
        }
        
        internal static string about_licenses_description {
            get {
                return ResourceManager.GetString("about_licenses_description", resourceCulture);
            }
        }
        
        internal static string view_licenses {
            get {
                return ResourceManager.GetString("view_licenses", resourceCulture);
            }
        }
        
        internal static string progress_loading_url_data {
            get {
                return ResourceManager.GetString("progress_loading_url_data", resourceCulture);
            }
        }
        
        internal static string contributionform_save {
            get {
                return ResourceManager.GetString("contributionform_save", resourceCulture);
            }
        }
        
        internal static string contributiondetails_edit {
            get {
                return ResourceManager.GetString("contributiondetails_edit", resourceCulture);
            }
        }
        
        internal static string error_title_validationfailed {
            get {
                return ResourceManager.GetString("error_title_validationfailed", resourceCulture);
            }
        }
        
        internal static string error_description_validationfailed {
            get {
                return ResourceManager.GetString("error_description_validationfailed", resourceCulture);
            }
        }
        
        internal static string empty_state_title {
            get {
                return ResourceManager.GetString("empty_state_title", resourceCulture);
            }
        }
        
        internal static string empty_state_contributions {
            get {
                return ResourceManager.GetString("empty_state_contributions", resourceCulture);
            }
        }
        
        internal static string contribution_add {
            get {
                return ResourceManager.GetString("contribution_add", resourceCulture);
            }
        }
        
        internal static string empty_state_contributiontypes {
            get {
                return ResourceManager.GetString("empty_state_contributiontypes", resourceCulture);
            }
        }
        
        internal static string empty_state_contributiontechnologies {
            get {
                return ResourceManager.GetString("empty_state_contributiontechnologies", resourceCulture);
            }
        }
        
        internal static string empty_state_noresultcontributiontechnologies {
            get {
                return ResourceManager.GetString("empty_state_noresultcontributiontechnologies", resourceCulture);
            }
        }
        
        internal static string empty_state_visibilities {
            get {
                return ResourceManager.GetString("empty_state_visibilities", resourceCulture);
            }
        }
        
        internal static string error_offline {
            get {
                return ResourceManager.GetString("error_offline", resourceCulture);
            }
        }
        
        internal static string error_offline_title {
            get {
                return ResourceManager.GetString("error_offline_title", resourceCulture);
            }
        }
        
        internal static string error_logoutwhileoffline {
            get {
                return ResourceManager.GetString("error_logoutwhileoffline", resourceCulture);
            }
        }
        
        internal static string offline_contributions {
            get {
                return ResourceManager.GetString("offline_contributions", resourceCulture);
            }
        }
        
        internal static string error_couldntchangeicon {
            get {
                return ResourceManager.GetString("error_couldntchangeicon", resourceCulture);
            }
        }
        
        internal static string error_couldntchangetheme {
            get {
                return ResourceManager.GetString("error_couldntchangetheme", resourceCulture);
            }
        }
        
        internal static string error_couldntchangelanguage {
            get {
                return ResourceManager.GetString("error_couldntchangelanguage", resourceCulture);
            }
        }
        
        internal static string error_title {
            get {
                return ResourceManager.GetString("error_title", resourceCulture);
            }
        }
        
        internal static string error_data_not_loaded {
            get {
                return ResourceManager.GetString("error_data_not_loaded", resourceCulture);
            }
        }
        
        internal static string error_couldntloadmorecontributions {
            get {
                return ResourceManager.GetString("error_couldntloadmorecontributions", resourceCulture);
            }
        }
        
        internal static string error_couldntsavecontribution {
            get {
                return ResourceManager.GetString("error_couldntsavecontribution", resourceCulture);
            }
        }
        
        internal static string error_couldntrefreshprofile {
            get {
                return ResourceManager.GetString("error_couldntrefreshprofile", resourceCulture);
            }
        }
        
        internal static string field_number_of_articles {
            get {
                return ResourceManager.GetString("field_number_of_articles", resourceCulture);
            }
        }
        
        internal static string field_number_of_views {
            get {
                return ResourceManager.GetString("field_number_of_views", resourceCulture);
            }
        }
        
        internal static string field_number_of_posts {
            get {
                return ResourceManager.GetString("field_number_of_posts", resourceCulture);
            }
        }
        
        internal static string field_number_of_subscribers {
            get {
                return ResourceManager.GetString("field_number_of_subscribers", resourceCulture);
            }
        }
        
        internal static string field_annual_unique_visitors {
            get {
                return ResourceManager.GetString("field_annual_unique_visitors", resourceCulture);
            }
        }
        
        internal static string field_number_of_books {
            get {
                return ResourceManager.GetString("field_number_of_books", resourceCulture);
            }
        }
        
        internal static string field_copies_sold {
            get {
                return ResourceManager.GetString("field_copies_sold", resourceCulture);
            }
        }
        
        internal static string field_number_of_conferences {
            get {
                return ResourceManager.GetString("field_number_of_conferences", resourceCulture);
            }
        }
        
        internal static string field_number_of_visitors {
            get {
                return ResourceManager.GetString("field_number_of_visitors", resourceCulture);
            }
        }
        
        internal static string field_prs_issues_submissions {
            get {
                return ResourceManager.GetString("field_prs_issues_submissions", resourceCulture);
            }
        }
        
        internal static string field_number_of_threads_moderated {
            get {
                return ResourceManager.GetString("field_number_of_threads_moderated", resourceCulture);
            }
        }
        
        internal static string field_number_of_answers {
            get {
                return ResourceManager.GetString("field_number_of_answers", resourceCulture);
            }
        }
        
        internal static string field_views_of_answers {
            get {
                return ResourceManager.GetString("field_views_of_answers", resourceCulture);
            }
        }
        
        internal static string field_number_of_mentorship_activity {
            get {
                return ResourceManager.GetString("field_number_of_mentorship_activity", resourceCulture);
            }
        }
        
        internal static string field_number_of_mentees {
            get {
                return ResourceManager.GetString("field_number_of_mentees", resourceCulture);
            }
        }
        
        internal static string field_number_of_projects {
            get {
                return ResourceManager.GetString("field_number_of_projects", resourceCulture);
            }
        }
        
        internal static string field_projects {
            get {
                return ResourceManager.GetString("field_projects", resourceCulture);
            }
        }
        
        internal static string field_contributions {
            get {
                return ResourceManager.GetString("field_contributions", resourceCulture);
            }
        }
        
        internal static string field_meetings {
            get {
                return ResourceManager.GetString("field_meetings", resourceCulture);
            }
        }
        
        internal static string field_members {
            get {
                return ResourceManager.GetString("field_members", resourceCulture);
            }
        }
        
        internal static string field_number_of_attendees {
            get {
                return ResourceManager.GetString("field_number_of_attendees", resourceCulture);
            }
        }
        
        internal static string field_annual_quantity {
            get {
                return ResourceManager.GetString("field_annual_quantity", resourceCulture);
            }
        }
        
        internal static string field_annual_reach {
            get {
                return ResourceManager.GetString("field_annual_reach", resourceCulture);
            }
        }
        
        internal static string field_number_of_events_participated {
            get {
                return ResourceManager.GetString("field_number_of_events_participated", resourceCulture);
            }
        }
        
        internal static string field_number_of_feedbacks_provided {
            get {
                return ResourceManager.GetString("field_number_of_feedbacks_provided", resourceCulture);
            }
        }
        
        internal static string field_number_of_samples {
            get {
                return ResourceManager.GetString("field_number_of_samples", resourceCulture);
            }
        }
        
        internal static string field_number_of_downloads {
            get {
                return ResourceManager.GetString("field_number_of_downloads", resourceCulture);
            }
        }
        
        internal static string field_number_of_sites {
            get {
                return ResourceManager.GetString("field_number_of_sites", resourceCulture);
            }
        }
        
        internal static string field_number_of_talks {
            get {
                return ResourceManager.GetString("field_number_of_talks", resourceCulture);
            }
        }
        
        internal static string field_attendees_of_talks {
            get {
                return ResourceManager.GetString("field_attendees_of_talks", resourceCulture);
            }
        }
        
        internal static string field_number_of_followers {
            get {
                return ResourceManager.GetString("field_number_of_followers", resourceCulture);
            }
        }
        
        internal static string field_number_of_videos {
            get {
                return ResourceManager.GetString("field_number_of_videos", resourceCulture);
            }
        }
        
        internal static string field_number_of_events {
            get {
                return ResourceManager.GetString("field_number_of_events", resourceCulture);
            }
        }
        
        internal static string onboarding_1_title {
            get {
                return ResourceManager.GetString("onboarding_1_title", resourceCulture);
            }
        }
        
        internal static string onboarding_1_description {
            get {
                return ResourceManager.GetString("onboarding_1_description", resourceCulture);
            }
        }
        
        internal static string onboarding_3_title {
            get {
                return ResourceManager.GetString("onboarding_3_title", resourceCulture);
            }
        }
        
        internal static string onboarding_3_description {
            get {
                return ResourceManager.GetString("onboarding_3_description", resourceCulture);
            }
        }
        
        internal static string about_credits_description {
            get {
                return ResourceManager.GetString("about_credits_description", resourceCulture);
            }
        }
        
        internal static string about_credits_title {
            get {
                return ResourceManager.GetString("about_credits_title", resourceCulture);
            }
        }
        
        internal static string acknowledgementtype_tester {
            get {
                return ResourceManager.GetString("acknowledgementtype_tester", resourceCulture);
            }
        }
        
        internal static string acknowledgementtype_translator {
            get {
                return ResourceManager.GetString("acknowledgementtype_translator", resourceCulture);
            }
        }
        
        internal static string sign_in {
            get {
                return ResourceManager.GetString("sign_in", resourceCulture);
            }
        }
        
        internal static string swipe_to_continue {
            get {
                return ResourceManager.GetString("swipe_to_continue", resourceCulture);
            }
        }
        
        internal static string try_with_demo_account {
            get {
                return ResourceManager.GetString("try_with_demo_account", resourceCulture);
            }
        }
        
        internal static string appiconpicker_title {
            get {
                return ResourceManager.GetString("appiconpicker_title", resourceCulture);
            }
        }
        
        internal static string please_reboot_app_language_change {
            get {
                return ResourceManager.GetString("please_reboot_app_language_change", resourceCulture);
            }
        }
    }
}
