//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVP.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations_es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations_es() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVP.Resources.Translations.es", typeof(Translations_es).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin las increíbles personas que se enumeran a continuación, esta app no habría sido posible. Por lo tanto, se han ganado un lugar aquí para celebrar sus contribuciones..
        /// </summary>
        internal static string about_credits_description {
            get {
                return ResourceManager.GetString("about_credits_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créditos.
        /// </summary>
        internal static string about_credits_title {
            get {
                return ResourceManager.GetString("about_credits_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta app se para sobre los hombros de gigantes sin los cuales su creación no sería posible. Si deseas saber quiénes son, consulta las licencias de sus increíbles piezas de software..
        /// </summary>
        internal static string about_licenses_description {
            get {
                return ResourceManager.GetString("about_licenses_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licencias.
        /// </summary>
        internal static string about_licenses_title {
            get {
                return ResourceManager.GetString("about_licenses_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta app es completamente de código abierto. Si te gusta la aplicación, siéntete libre de convertirte en patrocinador de GitHub, comprándome una taza de café digital al mes ☕️.
        /// </summary>
        internal static string about_opensource_description {
            get {
                return ResourceManager.GetString("about_opensource_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código abierto.
        /// </summary>
        internal static string about_opensource_title {
            get {
                return ResourceManager.GetString("about_opensource_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acerca de esta app.
        /// </summary>
        internal static string about_title {
            get {
                return ResourceManager.GetString("about_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siempre ha existido la necesidad de que los MVP de Microsoft gestionen las actividades de su comunidad de una forma más sencilla. El portal en línea funciona bien, pero tener algo similar en el bolsillo para crear actividades sobre la marcha es realmente genial. ¡Para eso es este proyecto!.
        /// </summary>
        internal static string about_why_description {
            get {
                return ResourceManager.GetString("about_why_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Por qué se desarrollo esta app?.
        /// </summary>
        internal static string about_why_title {
            get {
                return ResourceManager.GetString("about_why_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tester.
        /// </summary>
        internal static string acknowledgementtype_tester {
            get {
                return ResourceManager.GetString("acknowledgementtype_tester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traductor.
        /// </summary>
        internal static string acknowledgementtype_translator {
            get {
                return ResourceManager.GetString("acknowledgementtype_translator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Áreas de contribución adicionales.
        /// </summary>
        internal static string additionaltechnologypicker_title {
            get {
                return ResourceManager.GetString("additionaltechnologypicker_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tus credenciales caducaron y no pudimos salvar el día. Por lo tanto, has sido desconectado. Vuelve a iniciar sesión para continuar..
        /// </summary>
        internal static string alert_error_unauthorized {
            get {
                return ResourceManager.GetString("alert_error_unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conviértete en patrocinador.
        /// </summary>
        internal static string becomesponsor {
            get {
                return ResourceManager.GetString("becomesponsor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar contribución.
        /// </summary>
        internal static string button_delete_contribution {
            get {
                return ResourceManager.GetString("button_delete_contribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notamos una URL en su portapapeles. ¿Quieres que intentemos precompletar una actividad a partir de eso?.
        /// </summary>
        internal static string clipboard_description {
            get {
                return ResourceManager.GetString("clipboard_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¡Eso luce genial!.
        /// </summary>
        internal static string clipboard_title {
            get {
                return ResourceManager.GetString("clipboard_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar.
        /// </summary>
        internal static string contribution_add {
            get {
                return ResourceManager.GetString("contribution_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿Estás seguro de que deseas eliminar esta contribución? No puedes deshacer esto..
        /// </summary>
        internal static string contributiondetail_deleteconfirmation {
            get {
                return ResourceManager.GetString("contributiondetail_deleteconfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo borrar tu contribución. ¿Quizás ya se eliminó o tuvo lugar en el período de adjudicación anterior?.
        /// </summary>
        internal static string contributiondetail_notdeleted {
            get {
                return ResourceManager.GetString("contributiondetail_notdeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        internal static string contributiondetails_edit {
            get {
                return ResourceManager.GetString("contributiondetails_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalles de la actividad.
        /// </summary>
        internal static string contributiondetails_title {
            get {
                return ResourceManager.GetString("contributiondetails_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona el tipo de actividad que mejor se adapte a esta actividad..
        /// </summary>
        internal static string contributionform_activitytype_placeholder {
            get {
                return ResourceManager.GetString("contributionform_activitytype_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona hasta 2 áreas tecnológicas adicionales que también pueden aplicarse a esta actividad..
        /// </summary>
        internal static string contributionform_additionaltechnologyarea_placeholder {
            get {
                return ResourceManager.GetString("contributionform_additionaltechnologyarea_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardar.
        /// </summary>
        internal static string contributionform_save {
            get {
                return ResourceManager.GetString("contributionform_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona el área de tecnología que es el enfoque principal de esta actividad..
        /// </summary>
        internal static string contributionform_technologyarea_placeholder {
            get {
                return ResourceManager.GetString("contributionform_technologyarea_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu envío de contribución para el ciclo de premios de julio debe ser para actividades comunitarias entre {0} y {1}. Las actividades de la comunidad enviadas desde {1} y posteriores se llevarán a cabo para su consideración futura..
        /// </summary>
        internal static string contributionform_timeframememo {
            get {
                return ResourceManager.GetString("contributionform_timeframememo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar contribución.
        /// </summary>
        internal static string contributionform_title_add {
            get {
                return ResourceManager.GetString("contributionform_title_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar contribución.
        /// </summary>
        internal static string contributionform_title_edit {
            get {
                return ResourceManager.GetString("contributionform_title_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona el nivel de visibilidad de esta actividad..
        /// </summary>
        internal static string contributionform_visibility_placeholder {
            get {
                return ResourceManager.GetString("contributionform_visibility_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividades de la comunidad.
        /// </summary>
        internal static string contributions_title {
            get {
                return ResourceManager.GetString("contributions_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Área de contribución primaria.
        /// </summary>
        internal static string contributiontechnologypicker_title {
            get {
                return ResourceManager.GetString("contributiontechnologypicker_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de actividad.
        /// </summary>
        internal static string contributiontypepicker_title {
            get {
                return ResourceManager.GetString("contributiontypepicker_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pudimos encontrar ninguna contribución. Agrega una nueva contribución o actualice para intentar recuperar sus datos existentes..
        /// </summary>
        internal static string empty_state_contributions {
            get {
                return ResourceManager.GetString("empty_state_contributions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pudimos encontrar áreas de contribución. Intenta actualizar..
        /// </summary>
        internal static string empty_state_contributiontechnologies {
            get {
                return ResourceManager.GetString("empty_state_contributiontechnologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pudimos encontrar ningún tipo de contribución. Intenta actualizar..
        /// </summary>
        internal static string empty_state_contributiontypes {
            get {
                return ResourceManager.GetString("empty_state_contributiontypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu consulta de búsqueda no arrojó resultados. Prueba con una consulta de búsqueda diferente..
        /// </summary>
        internal static string empty_state_noresultcontributiontechnologies {
            get {
                return ResourceManager.GetString("empty_state_noresultcontributiontechnologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aah... ¡Está vacío aquí!.
        /// </summary>
        internal static string empty_state_title {
            get {
                return ResourceManager.GetString("empty_state_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No pudimos encontrar ninguna visibilidad. Intenta actualizar..
        /// </summary>
        internal static string empty_state_visibilities {
            get {
                return ResourceManager.GetString("empty_state_visibilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logramos hacer una solicitud que no estaba del todo bien. Inténtalo de nuevo más tarde..
        /// </summary>
        internal static string error_badrequest {
            get {
                return ResourceManager.GetString("error_badrequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu icono no se pudo cambiar. Por favor, inténtalo de nuevo más tarde..
        /// </summary>
        internal static string error_couldntchangeicon {
            get {
                return ResourceManager.GetString("error_couldntchangeicon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo cambiar tu idioma. Por favor, inténtalo de nuevo más tarde..
        /// </summary>
        internal static string error_couldntchangelanguage {
            get {
                return ResourceManager.GetString("error_couldntchangelanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tu tema no se pudo cambiar. Por favor, inténtalo de nuevo más tarde..
        /// </summary>
        internal static string error_couldntchangetheme {
            get {
                return ResourceManager.GetString("error_couldntchangetheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudieron cargar más contribuciones. No estamos muy seguros de por qué, pero se ha registrado un error. Por favor, inténtalo de nuevo más tarde..
        /// </summary>
        internal static string error_couldntloadmorecontributions {
            get {
                return ResourceManager.GetString("error_couldntloadmorecontributions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo actualizar la información de tu perfil. No estamos muy seguros de por qué, pero se ha registrado un error. Por favor, inténtalo de nuevo más tarde..
        /// </summary>
        internal static string error_couldntrefreshprofile {
            get {
                return ResourceManager.GetString("error_couldntrefreshprofile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo guardar esta contribución. No estamos muy seguros de por qué, pero se ha registrado un error. Por favor, inténtalo de nuevo más tarde..
        /// </summary>
        internal static string error_couldntsavecontribution {
            get {
                return ResourceManager.GetString("error_couldntsavecontribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudieron cargar los datos. No estamos muy seguros de por qué, pero se ha registrado un error. Puedes intentar actualizar o volver a intentarlo más tarde..
        /// </summary>
        internal static string error_data_not_loaded {
            get {
                return ResourceManager.GetString("error_data_not_loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se completaron todos los campos obligatorios. Completa el formulario e intenta guardar nuevamente..
        /// </summary>
        internal static string error_description_validationfailed {
            get {
                return ResourceManager.GetString("error_description_validationfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualmente no tienes conexión a Internet. Esto puede hacer que no pueda volver a iniciar sesión. ¿Estás seguro de que quieres continuar?.
        /// </summary>
        internal static string error_logoutwhileoffline {
            get {
                return ResourceManager.GetString("error_logoutwhileoffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo autenticarlo con las credenciales proporcionadas. ¿Estás seguro de que está utilizando la cuenta asociada a su ID de MVP?.
        /// </summary>
        internal static string error_nomvpaccount {
            get {
                return ResourceManager.GetString("error_nomvpaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta acción no se puede realizar sin una conexión a Internet. Por favor, inténtalo de nuevo más tarde..
        /// </summary>
        internal static string error_offline {
            get {
                return ResourceManager.GetString("error_offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin conexión a Internet.
        /// </summary>
        internal static string error_offline_title {
            get {
                return ResourceManager.GetString("error_offline_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se pudo procesar su solicitud. Inténtalo de nuevo más tarde..
        /// </summary>
        internal static string error_servererror {
            get {
                return ResourceManager.GetString("error_servererror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algo salió mal.
        /// </summary>
        internal static string error_title {
            get {
                return ResourceManager.GetString("error_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validación fallida.
        /// </summary>
        internal static string error_title_validationfailed {
            get {
                return ResourceManager.GetString("error_title_validationfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algo salió mal que no esperábamos que sucediera. Se ha registrado un error y lo investigaremos lo antes posible..
        /// </summary>
        internal static string error_unexpected {
            get {
                return ResourceManager.GetString("error_unexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha de actividad.
        /// </summary>
        internal static string field_activity_date {
            get {
                return ResourceManager.GetString("field_activity_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de actividad.
        /// </summary>
        internal static string field_activity_type {
            get {
                return ResourceManager.GetString("field_activity_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Áreas de contribución adicionales.
        /// </summary>
        internal static string field_additional_contribution_areas {
            get {
                return ResourceManager.GetString("field_additional_contribution_areas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cantidad Anual.
        /// </summary>
        internal static string field_annual_quantity {
            get {
                return ResourceManager.GetString("field_annual_quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alcance Anual.
        /// </summary>
        internal static string field_annual_reach {
            get {
                return ResourceManager.GetString("field_annual_reach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visitantes Únicos Anuales.
        /// </summary>
        internal static string field_annual_unique_visitors {
            get {
                return ResourceManager.GetString("field_annual_unique_visitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asistentes a Charlas.
        /// </summary>
        internal static string field_attendees_of_talks {
            get {
                return ResourceManager.GetString("field_attendees_of_talks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contribuciones.
        /// </summary>
        internal static string field_contributions {
            get {
                return ResourceManager.GetString("field_contributions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copias Vendidas.
        /// </summary>
        internal static string field_copies_sold {
            get {
                return ResourceManager.GetString("field_copies_sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descripción.
        /// </summary>
        internal static string field_description {
            get {
                return ResourceManager.GetString("field_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reuniones.
        /// </summary>
        internal static string field_meetings {
            get {
                return ResourceManager.GetString("field_meetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miembros.
        /// </summary>
        internal static string field_members {
            get {
                return ResourceManager.GetString("field_members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero de Respuestas.
        /// </summary>
        internal static string field_number_of_answers {
            get {
                return ResourceManager.GetString("field_number_of_answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Artículos.
        /// </summary>
        internal static string field_number_of_articles {
            get {
                return ResourceManager.GetString("field_number_of_articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Asistentes.
        /// </summary>
        internal static string field_number_of_attendees {
            get {
                return ResourceManager.GetString("field_number_of_attendees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero de Libros.
        /// </summary>
        internal static string field_number_of_books {
            get {
                return ResourceManager.GetString("field_number_of_books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero de Conferencias.
        /// </summary>
        internal static string field_number_of_conferences {
            get {
                return ResourceManager.GetString("field_number_of_conferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Descargas.
        /// </summary>
        internal static string field_number_of_downloads {
            get {
                return ResourceManager.GetString("field_number_of_downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero de Eventos.
        /// </summary>
        internal static string field_number_of_events {
            get {
                return ResourceManager.GetString("field_number_of_events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Eventos Participados.
        /// </summary>
        internal static string field_number_of_events_participated {
            get {
                return ResourceManager.GetString("field_number_of_events_participated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Comentarios Proporcionados.
        /// </summary>
        internal static string field_number_of_feedbacks_provided {
            get {
                return ResourceManager.GetString("field_number_of_feedbacks_provided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero de Seguidores.
        /// </summary>
        internal static string field_number_of_followers {
            get {
                return ResourceManager.GetString("field_number_of_followers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Aprendices.
        /// </summary>
        internal static string field_number_of_mentees {
            get {
                return ResourceManager.GetString("field_number_of_mentees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Actividad de Tutoría.
        /// </summary>
        internal static string field_number_of_mentorship_activity {
            get {
                return ResourceManager.GetString("field_number_of_mentorship_activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Publicaciones.
        /// </summary>
        internal static string field_number_of_posts {
            get {
                return ResourceManager.GetString("field_number_of_posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero de Proyectos.
        /// </summary>
        internal static string field_number_of_projects {
            get {
                return ResourceManager.GetString("field_number_of_projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Ejemplos.
        /// </summary>
        internal static string field_number_of_samples {
            get {
                return ResourceManager.GetString("field_number_of_samples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Sitios.
        /// </summary>
        internal static string field_number_of_sites {
            get {
                return ResourceManager.GetString("field_number_of_sites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numero de Suscriptores.
        /// </summary>
        internal static string field_number_of_subscribers {
            get {
                return ResourceManager.GetString("field_number_of_subscribers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Charlas.
        /// </summary>
        internal static string field_number_of_talks {
            get {
                return ResourceManager.GetString("field_number_of_talks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Hilos Moderados.
        /// </summary>
        internal static string field_number_of_threads_moderated {
            get {
                return ResourceManager.GetString("field_number_of_threads_moderated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Videos.
        /// </summary>
        internal static string field_number_of_videos {
            get {
                return ResourceManager.GetString("field_number_of_videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Vistas.
        /// </summary>
        internal static string field_number_of_views {
            get {
                return ResourceManager.GetString("field_number_of_views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Visitantes.
        /// </summary>
        internal static string field_number_of_visitors {
            get {
                return ResourceManager.GetString("field_number_of_visitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Área de contribución primaria.
        /// </summary>
        internal static string field_primary_contribution_area {
            get {
                return ResourceManager.GetString("field_primary_contribution_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proyecto(s).
        /// </summary>
        internal static string field_projects {
            get {
                return ResourceManager.GetString("field_projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull Requests/Issues/Submissions.
        /// </summary>
        internal static string field_prs_issues_submissions {
            get {
                return ResourceManager.GetString("field_prs_issues_submissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título de la actividad.
        /// </summary>
        internal static string field_title {
            get {
                return ResourceManager.GetString("field_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string field_url {
            get {
                return ResourceManager.GetString("field_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vistas de Respuestas.
        /// </summary>
        internal static string field_views_of_answers {
            get {
                return ResourceManager.GetString("field_views_of_answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibilidad.
        /// </summary>
        internal static string field_visibility {
            get {
                return ResourceManager.GetString("field_visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negro.
        /// </summary>
        internal static string icon_black {
            get {
                return ResourceManager.GetString("icon_black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azul oscuro.
        /// </summary>
        internal static string icon_darkblue {
            get {
                return ResourceManager.GetString("icon_darkblue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predeterminado.
        /// </summary>
        internal static string icon_default {
            get {
                return ResourceManager.GetString("icon_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arco iris.
        /// </summary>
        internal static string icon_rainbow {
            get {
                return ResourceManager.GetString("icon_rainbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blanco.
        /// </summary>
        internal static string icon_white {
            get {
                return ResourceManager.GetString("icon_white", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nederlands.
        /// </summary>
        internal static string language_dutch {
            get {
                return ResourceManager.GetString("language_dutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string language_english {
            get {
                return ResourceManager.GetString("language_english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        internal static string language_spanish {
            get {
                return ResourceManager.GetString("language_spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lenguaje.
        /// </summary>
        internal static string languagepicker_title {
            get {
                return ResourceManager.GetString("languagepicker_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licencias.
        /// </summary>
        internal static string licenses_title {
            get {
                return ResourceManager.GetString("licenses_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cerrar sesión.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualmente no tienes conexión a Internet. Esto nos impide cargar tus contribuciones. Por favor, inténtalo de nuevo más tarde..
        /// </summary>
        internal static string offline_contributions {
            get {
                return ResourceManager.GetString("offline_contributions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administra todas las actividades de tu comunidad desde la palma de tu mano..
        /// </summary>
        internal static string onboarding_1_description {
            get {
                return ResourceManager.GetString("onboarding_1_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple y eficaz.
        /// </summary>
        internal static string onboarding_1_title {
            get {
                return ResourceManager.GetString("onboarding_1_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crea contribuciones directamente basadas en una URL en su portapapeles. Prellenando todo lo que podamos para que puedas agregar rápidamente nuevas contribuciones..
        /// </summary>
        internal static string onboarding_3_description {
            get {
                return ResourceManager.GetString("onboarding_3_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agregar Rápido.
        /// </summary>
        internal static string onboarding_3_title {
            get {
                return ResourceManager.GetString("onboarding_3_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuraciones.
        /// </summary>
        internal static string profile_title {
            get {
                return ResourceManager.GetString("profile_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obteniendo metadatos de URL....
        /// </summary>
        internal static string progress_loading_url_data {
            get {
                return ResourceManager.GetString("progress_loading_url_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guardando....
        /// </summary>
        internal static string progress_saving {
            get {
                return ResourceManager.GetString("progress_saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscando....
        /// </summary>
        internal static string search_placeholder {
            get {
                return ResourceManager.GetString("search_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿No te gusta el ícono de la aplicación que elegimos para ti? Tenemos opciones alternativas disponibles. Si tiene ideas para otras, ¡No dudes en contactarnos!.
        /// </summary>
        internal static string setting_appicon_description {
            get {
                return ResourceManager.GetString("setting_appicon_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icono de la aplicación.
        /// </summary>
        internal static string setting_appicon_title {
            get {
                return ResourceManager.GetString("setting_appicon_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta aplicación se puede utilizar tanto en modo claro como oscuro. De forma predeterminada, elegirá lo que esté configurado en tu dispositivo. Si alguno de los temas te gusta, también puedes forzar un tema específico aquí..
        /// </summary>
        internal static string setting_apptheme_description {
            get {
                return ResourceManager.GetString("setting_apptheme_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema de la aplicación.
        /// </summary>
        internal static string setting_apptheme_title {
            get {
                return ResourceManager.GetString("setting_apptheme_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si tienes una URL válida en tu portapapeles mientras agregas una contribución, se te preguntará si los metadatos de esa URL deben usarse para completar tu contribución..
        /// </summary>
        internal static string setting_contributionfromurl_description {
            get {
                return ResourceManager.GetString("setting_contributionfromurl_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crear contribución desde URL.
        /// </summary>
        internal static string setting_contributionfromurl_title {
            get {
                return ResourceManager.GetString("setting_contributionfromurl_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De forma predeterminada, seleccionamos el idioma que está utilizando en su dispositivo si hay traducciones disponibles. Sin embargo, si deseas utilizar esta aplicación en un idioma diferente, puedes remplazarlo aquí..
        /// </summary>
        internal static string setting_language_description {
            get {
                return ResourceManager.GetString("setting_language_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lenguaje.
        /// </summary>
        internal static string setting_language_title {
            get {
                return ResourceManager.GetString("setting_language_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomando las áreas de contribución....
        /// </summary>
        internal static string splash_contributionareas {
            get {
                return ResourceManager.GetString("splash_contributionareas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sincronizando los tipos de contribución....
        /// </summary>
        internal static string splash_contributiontypes {
            get {
                return ResourceManager.GetString("splash_contributiontypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparando las cosas....
        /// </summary>
        internal static string splash_gettingready {
            get {
                return ResourceManager.GetString("splash_gettingready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poniendo visibilidades en su lugar....
        /// </summary>
        internal static string splash_visibilities {
            get {
                return ResourceManager.GetString("splash_visibilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividades.
        /// </summary>
        internal static string tabs_activities {
            get {
                return ResourceManager.GetString("tabs_activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insignias.
        /// </summary>
        internal static string tabs_badges {
            get {
                return ResourceManager.GetString("tabs_badges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuraciones.
        /// </summary>
        internal static string tabs_settings {
            get {
                return ResourceManager.GetString("tabs_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estadísticas.
        /// </summary>
        internal static string tabs_statistics {
            get {
                return ResourceManager.GetString("tabs_statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oscuro.
        /// </summary>
        internal static string theme_dark {
            get {
                return ResourceManager.GetString("theme_dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claro.
        /// </summary>
        internal static string theme_light {
            get {
                return ResourceManager.GetString("theme_light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predeterminado de Sistema.
        /// </summary>
        internal static string theme_systemdefault {
            get {
                return ResourceManager.GetString("theme_systemdefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema de la aplicación.
        /// </summary>
        internal static string themepicker_title {
            get {
                return ResourceManager.GetString("themepicker_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} es un campo obligatorio..
        /// </summary>
        internal static string validation_variablefield {
            get {
                return ResourceManager.GetString("validation_variablefield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ver licencias.
        /// </summary>
        internal static string view_licenses {
            get {
                return ResourceManager.GetString("view_licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibilidad.
        /// </summary>
        internal static string visibility_title {
            get {
                return ResourceManager.GetString("visibility_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta actividad se registró en la ventana de contribución anterior y, por lo tanto, no se puede editar ni eliminar..
        /// </summary>
        internal static string warning_description_activitylocked {
            get {
                return ResourceManager.GetString("warning_description_activitylocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espera....
        /// </summary>
        internal static string warning_title {
            get {
                return ResourceManager.GetString("warning_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actividad bloqueada.
        /// </summary>
        internal static string warning_title_activitylocked {
            get {
                return ResourceManager.GetString("warning_title_activitylocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Si.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
