//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVP.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations_nl {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations_nl() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MVP.Resources.Translations.nl", typeof(Translations_nl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string contributions_title {
            get {
                return ResourceManager.GetString("contributions_title", resourceCulture);
            }
        }
        
        internal static string search_placeholder {
            get {
                return ResourceManager.GetString("search_placeholder", resourceCulture);
            }
        }
        
        internal static string profile_title {
            get {
                return ResourceManager.GetString("profile_title", resourceCulture);
            }
        }
        
        internal static string setting_contributionfromurl_title {
            get {
                return ResourceManager.GetString("setting_contributionfromurl_title", resourceCulture);
            }
        }
        
        internal static string setting_contributionfromurl_desc {
            get {
                return ResourceManager.GetString("setting_contributionfromurl_desc", resourceCulture);
            }
        }
        
        internal static string setting_apptheme_title {
            get {
                return ResourceManager.GetString("setting_apptheme_title", resourceCulture);
            }
        }
        
        internal static string setting_apptheme_desc {
            get {
                return ResourceManager.GetString("setting_apptheme_desc", resourceCulture);
            }
        }
        
        internal static string button_logout {
            get {
                return ResourceManager.GetString("button_logout", resourceCulture);
            }
        }
        
        internal static string tabs_activities {
            get {
                return ResourceManager.GetString("tabs_activities", resourceCulture);
            }
        }
        
        internal static string tabs_statistics {
            get {
                return ResourceManager.GetString("tabs_statistics", resourceCulture);
            }
        }
        
        internal static string tabs_badges {
            get {
                return ResourceManager.GetString("tabs_badges", resourceCulture);
            }
        }
        
        internal static string tabs_settings {
            get {
                return ResourceManager.GetString("tabs_settings", resourceCulture);
            }
        }
        
        internal static string contributionform_title_add {
            get {
                return ResourceManager.GetString("contributionform_title_add", resourceCulture);
            }
        }
        
        internal static string contributionform_title_edit {
            get {
                return ResourceManager.GetString("contributionform_title_edit", resourceCulture);
            }
        }
        
        internal static string language_english {
            get {
                return ResourceManager.GetString("language_english", resourceCulture);
            }
        }
        
        internal static string language_dutch {
            get {
                return ResourceManager.GetString("language_dutch", resourceCulture);
            }
        }
        
        internal static string languagepicker_title {
            get {
                return ResourceManager.GetString("languagepicker_title", resourceCulture);
            }
        }
        
        internal static string contributiondetails_title {
            get {
                return ResourceManager.GetString("contributiondetails_title", resourceCulture);
            }
        }
        
        internal static string field_activity_type {
            get {
                return ResourceManager.GetString("field_activity_type", resourceCulture);
            }
        }
        
        internal static string field_title {
            get {
                return ResourceManager.GetString("field_title", resourceCulture);
            }
        }
        
        internal static string field_primary_contribution_area {
            get {
                return ResourceManager.GetString("field_primary_contribution_area", resourceCulture);
            }
        }
        
        internal static string field_url {
            get {
                return ResourceManager.GetString("field_url", resourceCulture);
            }
        }
        
        internal static string field_additional_contribution_areas {
            get {
                return ResourceManager.GetString("field_additional_contribution_areas", resourceCulture);
            }
        }
        
        internal static string field_activity_date {
            get {
                return ResourceManager.GetString("field_activity_date", resourceCulture);
            }
        }
        
        internal static string field_description {
            get {
                return ResourceManager.GetString("field_description", resourceCulture);
            }
        }
        
        internal static string field_visibility {
            get {
                return ResourceManager.GetString("field_visibility", resourceCulture);
            }
        }
        
        internal static string button_delete_contribution {
            get {
                return ResourceManager.GetString("button_delete_contribution", resourceCulture);
            }
        }
    }
}
