//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVP.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVP.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without the awesome people listed below this app would not have been possible. Therefore they have earned a spot in here to celebrate their contributions..
        /// </summary>
        internal static string about_credits_description {
            get {
                return ResourceManager.GetString("about_credits_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        internal static string about_credits_title {
            get {
                return ResourceManager.GetString("about_credits_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app stands on the shoulders of giants without whom its creation would not be possible. If you want to know who they are, check out the licenses for their awesome pieces of software..
        /// </summary>
        internal static string about_licenses_description {
            get {
                return ResourceManager.GetString("about_licenses_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        internal static string about_licenses_title {
            get {
                return ResourceManager.GetString("about_licenses_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app is completely open source. If you like the app, feel free to become a GitHub sponsor, buying me a digital cup of coffee a month ☕️.
        /// </summary>
        internal static string about_opensource_description {
            get {
                return ResourceManager.GetString("about_opensource_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open source.
        /// </summary>
        internal static string about_opensource_title {
            get {
                return ResourceManager.GetString("about_opensource_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About this app.
        /// </summary>
        internal static string about_title {
            get {
                return ResourceManager.GetString("about_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There has always been a need for Microsoft MVPs to manage their community activities in an easier way. The online portal works fine, but having a similar thing in your pocket to create activities on the fly is really cool. Which is what this project is for!.
        /// </summary>
        internal static string about_why_description {
            get {
                return ResourceManager.GetString("about_why_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why was this app built?.
        /// </summary>
        internal static string about_why_title {
            get {
                return ResourceManager.GetString("about_why_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tester.
        /// </summary>
        internal static string acknowledgementtype_tester {
            get {
                return ResourceManager.GetString("acknowledgementtype_tester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translator.
        /// </summary>
        internal static string acknowledgementtype_translator {
            get {
                return ResourceManager.GetString("acknowledgementtype_translator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional contribution areas.
        /// </summary>
        internal static string additionaltechnologypicker_title {
            get {
                return ResourceManager.GetString("additionaltechnologypicker_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your credentials have expired and they couldn&apos;t be refreshed. Therefore you were logged out. Please log in again to continue..
        /// </summary>
        internal static string alert_error_unauthorized {
            get {
                return ResourceManager.GetString("alert_error_unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Become a sponsor.
        /// </summary>
        internal static string becomesponsor {
            get {
                return ResourceManager.GetString("becomesponsor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete contribution.
        /// </summary>
        internal static string button_delete_contribution {
            get {
                return ResourceManager.GetString("button_delete_contribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We notice a URL on your clipboard. Do you want us to try to pre-fill an activity out of that?.
        /// </summary>
        internal static string clipboard_description {
            get {
                return ResourceManager.GetString("clipboard_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That looks cool!.
        /// </summary>
        internal static string clipboard_title {
            get {
                return ResourceManager.GetString("clipboard_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string contribution_add {
            get {
                return ResourceManager.GetString("contribution_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this contribution? You cannot undo this..
        /// </summary>
        internal static string contributiondetail_deleteconfirmation {
            get {
                return ResourceManager.GetString("contributiondetail_deleteconfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contribution could not be deleted. Perhaps it was already deleted, or it took place in the previous award period?.
        /// </summary>
        internal static string contributiondetail_notdeleted {
            get {
                return ResourceManager.GetString("contributiondetail_notdeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string contributiondetails_edit {
            get {
                return ResourceManager.GetString("contributiondetails_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity details.
        /// </summary>
        internal static string contributiondetails_title {
            get {
                return ResourceManager.GetString("contributiondetails_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the activity type that best fits this activity..
        /// </summary>
        internal static string contributionform_activitytype_placeholder {
            get {
                return ResourceManager.GetString("contributionform_activitytype_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select up to 2 additional technology areas that may also apply to this activity..
        /// </summary>
        internal static string contributionform_additionaltechnologyarea_placeholder {
            get {
                return ResourceManager.GetString("contributionform_additionaltechnologyarea_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string contributionform_save {
            get {
                return ResourceManager.GetString("contributionform_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the technology area that is the primary focus of this activity..
        /// </summary>
        internal static string contributionform_technologyarea_placeholder {
            get {
                return ResourceManager.GetString("contributionform_technologyarea_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your contribution submission for the July award cycle must be for community activities between {0} to {1}. Community activities submitted from {1} and beyond will be held for future consideration..
        /// </summary>
        internal static string contributionform_timeframememo {
            get {
                return ResourceManager.GetString("contributionform_timeframememo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add contribution.
        /// </summary>
        internal static string contributionform_title_add {
            get {
                return ResourceManager.GetString("contributionform_title_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit contribution.
        /// </summary>
        internal static string contributionform_title_edit {
            get {
                return ResourceManager.GetString("contributionform_title_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the visibility level of this activity..
        /// </summary>
        internal static string contributionform_visibility_placeholder {
            get {
                return ResourceManager.GetString("contributionform_visibility_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community activities.
        /// </summary>
        internal static string contributions_title {
            get {
                return ResourceManager.GetString("contributions_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary contribution area.
        /// </summary>
        internal static string contributiontechnologypicker_title {
            get {
                return ResourceManager.GetString("contributiontechnologypicker_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity type.
        /// </summary>
        internal static string contributiontypepicker_title {
            get {
                return ResourceManager.GetString("contributiontypepicker_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find any contributions. Add a new contribution or refresh to try and retrieve your existing data..
        /// </summary>
        internal static string empty_state_contributions {
            get {
                return ResourceManager.GetString("empty_state_contributions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find any contribution areas. Please try to refresh them..
        /// </summary>
        internal static string empty_state_contributiontechnologies {
            get {
                return ResourceManager.GetString("empty_state_contributiontechnologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find any contribution types. Please try to refresh them..
        /// </summary>
        internal static string empty_state_contributiontypes {
            get {
                return ResourceManager.GetString("empty_state_contributiontypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your search query returned no results. Please try a different search query..
        /// </summary>
        internal static string empty_state_noresultcontributiontechnologies {
            get {
                return ResourceManager.GetString("empty_state_noresultcontributiontechnologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooh...it&apos;s empty here!.
        /// </summary>
        internal static string empty_state_title {
            get {
                return ResourceManager.GetString("empty_state_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find any visibilities. Please try to refresh them..
        /// </summary>
        internal static string empty_state_visibilities {
            get {
                return ResourceManager.GetString("empty_state_visibilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t process your request. Try again later..
        /// </summary>
        internal static string error_badrequest {
            get {
                return ResourceManager.GetString("error_badrequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your icon couldn&apos;t be changed. Please try again later..
        /// </summary>
        internal static string error_couldntchangeicon {
            get {
                return ResourceManager.GetString("error_couldntchangeicon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your language couldn&apos;t be changed. Please try again later..
        /// </summary>
        internal static string error_couldntchangelanguage {
            get {
                return ResourceManager.GetString("error_couldntchangelanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your theme couldn&apos;t be changed. Please try again later..
        /// </summary>
        internal static string error_couldntchangetheme {
            get {
                return ResourceManager.GetString("error_couldntchangetheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t load more contributions. We&apos;re not quite sure why but an error has been logged. Please try again later..
        /// </summary>
        internal static string error_couldntloadmorecontributions {
            get {
                return ResourceManager.GetString("error_couldntloadmorecontributions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t refresh your profile information. We&apos;re not quite sure why but an error has been logged. Please try again later..
        /// </summary>
        internal static string error_couldntrefreshprofile {
            get {
                return ResourceManager.GetString("error_couldntrefreshprofile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t save this contribution. We&apos;re not quite sure why but an error has been logged. Please try again later..
        /// </summary>
        internal static string error_couldntsavecontribution {
            get {
                return ResourceManager.GetString("error_couldntsavecontribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data could not be loaded. We&apos;re not quite sure why but an error has been logged. You can try to refresh or try again later..
        /// </summary>
        internal static string error_data_not_loaded {
            get {
                return ResourceManager.GetString("error_data_not_loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all required fields were completed. Please complete the form and try saving again..
        /// </summary>
        internal static string error_description_validationfailed {
            get {
                return ResourceManager.GetString("error_description_validationfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You currently have no internet connection. This may cause you to not be able to log back in again. Are you sure you want to continue?.
        /// </summary>
        internal static string error_logoutwhileoffline {
            get {
                return ResourceManager.GetString("error_logoutwhileoffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t authenticate you using the provided credentials. Are you sure you are using the account associated to your MVP ID?.
        /// </summary>
        internal static string error_nomvpaccount {
            get {
                return ResourceManager.GetString("error_nomvpaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action cannot be performed without an internet connection. Please try again later..
        /// </summary>
        internal static string error_offline {
            get {
                return ResourceManager.GetString("error_offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection.
        /// </summary>
        internal static string error_offline_title {
            get {
                return ResourceManager.GetString("error_offline_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t process your request. Try again later..
        /// </summary>
        internal static string error_servererror {
            get {
                return ResourceManager.GetString("error_servererror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        internal static string error_title {
            get {
                return ResourceManager.GetString("error_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed.
        /// </summary>
        internal static string error_title_validationfailed {
            get {
                return ResourceManager.GetString("error_title_validationfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. An error has been logged and we will look into it as soon as possible..
        /// </summary>
        internal static string error_unexpected {
            get {
                return ResourceManager.GetString("error_unexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity date.
        /// </summary>
        internal static string field_activity_date {
            get {
                return ResourceManager.GetString("field_activity_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity type.
        /// </summary>
        internal static string field_activity_type {
            get {
                return ResourceManager.GetString("field_activity_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional contribution areas.
        /// </summary>
        internal static string field_additional_contribution_areas {
            get {
                return ResourceManager.GetString("field_additional_contribution_areas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Quantity.
        /// </summary>
        internal static string field_annual_quantity {
            get {
                return ResourceManager.GetString("field_annual_quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Reach.
        /// </summary>
        internal static string field_annual_reach {
            get {
                return ResourceManager.GetString("field_annual_reach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Unique Visitors.
        /// </summary>
        internal static string field_annual_unique_visitors {
            get {
                return ResourceManager.GetString("field_annual_unique_visitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendees of Talks.
        /// </summary>
        internal static string field_attendees_of_talks {
            get {
                return ResourceManager.GetString("field_attendees_of_talks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contributions.
        /// </summary>
        internal static string field_contributions {
            get {
                return ResourceManager.GetString("field_contributions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copies Sold.
        /// </summary>
        internal static string field_copies_sold {
            get {
                return ResourceManager.GetString("field_copies_sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string field_description {
            get {
                return ResourceManager.GetString("field_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meetings.
        /// </summary>
        internal static string field_meetings {
            get {
                return ResourceManager.GetString("field_meetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        internal static string field_members {
            get {
                return ResourceManager.GetString("field_members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Answers.
        /// </summary>
        internal static string field_number_of_answers {
            get {
                return ResourceManager.GetString("field_number_of_answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Articles.
        /// </summary>
        internal static string field_number_of_articles {
            get {
                return ResourceManager.GetString("field_number_of_articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Attendees.
        /// </summary>
        internal static string field_number_of_attendees {
            get {
                return ResourceManager.GetString("field_number_of_attendees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Books.
        /// </summary>
        internal static string field_number_of_books {
            get {
                return ResourceManager.GetString("field_number_of_books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Conferences.
        /// </summary>
        internal static string field_number_of_conferences {
            get {
                return ResourceManager.GetString("field_number_of_conferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Downloads.
        /// </summary>
        internal static string field_number_of_downloads {
            get {
                return ResourceManager.GetString("field_number_of_downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Events.
        /// </summary>
        internal static string field_number_of_events {
            get {
                return ResourceManager.GetString("field_number_of_events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Events Participated.
        /// </summary>
        internal static string field_number_of_events_participated {
            get {
                return ResourceManager.GetString("field_number_of_events_participated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Feedbacks Provided.
        /// </summary>
        internal static string field_number_of_feedbacks_provided {
            get {
                return ResourceManager.GetString("field_number_of_feedbacks_provided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Followers.
        /// </summary>
        internal static string field_number_of_followers {
            get {
                return ResourceManager.GetString("field_number_of_followers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Mentees.
        /// </summary>
        internal static string field_number_of_mentees {
            get {
                return ResourceManager.GetString("field_number_of_mentees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Mentorship Activity.
        /// </summary>
        internal static string field_number_of_mentorship_activity {
            get {
                return ResourceManager.GetString("field_number_of_mentorship_activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Posts.
        /// </summary>
        internal static string field_number_of_posts {
            get {
                return ResourceManager.GetString("field_number_of_posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Projects.
        /// </summary>
        internal static string field_number_of_projects {
            get {
                return ResourceManager.GetString("field_number_of_projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Samples.
        /// </summary>
        internal static string field_number_of_samples {
            get {
                return ResourceManager.GetString("field_number_of_samples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Sites.
        /// </summary>
        internal static string field_number_of_sites {
            get {
                return ResourceManager.GetString("field_number_of_sites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Subscribers.
        /// </summary>
        internal static string field_number_of_subscribers {
            get {
                return ResourceManager.GetString("field_number_of_subscribers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Talks.
        /// </summary>
        internal static string field_number_of_talks {
            get {
                return ResourceManager.GetString("field_number_of_talks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Threads Moderated.
        /// </summary>
        internal static string field_number_of_threads_moderated {
            get {
                return ResourceManager.GetString("field_number_of_threads_moderated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Videos.
        /// </summary>
        internal static string field_number_of_videos {
            get {
                return ResourceManager.GetString("field_number_of_videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Views.
        /// </summary>
        internal static string field_number_of_views {
            get {
                return ResourceManager.GetString("field_number_of_views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Visitors.
        /// </summary>
        internal static string field_number_of_visitors {
            get {
                return ResourceManager.GetString("field_number_of_visitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary contribution area.
        /// </summary>
        internal static string field_primary_contribution_area {
            get {
                return ResourceManager.GetString("field_primary_contribution_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project(s).
        /// </summary>
        internal static string field_projects {
            get {
                return ResourceManager.GetString("field_projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull Requests/Issues/Submissions.
        /// </summary>
        internal static string field_prs_issues_submissions {
            get {
                return ResourceManager.GetString("field_prs_issues_submissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title of activity.
        /// </summary>
        internal static string field_title {
            get {
                return ResourceManager.GetString("field_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string field_url {
            get {
                return ResourceManager.GetString("field_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views of Answers.
        /// </summary>
        internal static string field_views_of_answers {
            get {
                return ResourceManager.GetString("field_views_of_answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility.
        /// </summary>
        internal static string field_visibility {
            get {
                return ResourceManager.GetString("field_visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black.
        /// </summary>
        internal static string icon_black {
            get {
                return ResourceManager.GetString("icon_black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Blue.
        /// </summary>
        internal static string icon_darkblue {
            get {
                return ResourceManager.GetString("icon_darkblue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string icon_default {
            get {
                return ResourceManager.GetString("icon_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rainbow.
        /// </summary>
        internal static string icon_rainbow {
            get {
                return ResourceManager.GetString("icon_rainbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to White.
        /// </summary>
        internal static string icon_white {
            get {
                return ResourceManager.GetString("icon_white", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch.
        /// </summary>
        internal static string language_dutch {
            get {
                return ResourceManager.GetString("language_dutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string language_english {
            get {
                return ResourceManager.GetString("language_english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungarian.
        /// </summary>
        internal static string language_hungarian {
            get {
                return ResourceManager.GetString("language_hungarian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string languagepicker_title {
            get {
                return ResourceManager.GetString("languagepicker_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        internal static string licenses_title {
            get {
                return ResourceManager.GetString("licenses_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You currently have no internet connection. This prevents us from loading your contributions. Please try again later..
        /// </summary>
        internal static string offline_contributions {
            get {
                return ResourceManager.GetString("offline_contributions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage all of your community activities from the palm of your hand..
        /// </summary>
        internal static string onboarding_1_description {
            get {
                return ResourceManager.GetString("onboarding_1_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple and effective.
        /// </summary>
        internal static string onboarding_1_title {
            get {
                return ResourceManager.GetString("onboarding_1_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directly create contributions based on a URL on your clipboard. Pre-filling whatever Can for you allowing you to quickly add new contributions..
        /// </summary>
        internal static string onboarding_3_description {
            get {
                return ResourceManager.GetString("onboarding_3_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick Add.
        /// </summary>
        internal static string onboarding_3_title {
            get {
                return ResourceManager.GetString("onboarding_3_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string profile_title {
            get {
                return ResourceManager.GetString("profile_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting URL metadata....
        /// </summary>
        internal static string progress_loading_url_data {
            get {
                return ResourceManager.GetString("progress_loading_url_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        internal static string progress_saving {
            get {
                return ResourceManager.GetString("progress_saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string search_placeholder {
            get {
                return ResourceManager.GetString("search_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t like the default app icon? Alternative options are available..
        /// </summary>
        internal static string setting_appicon_description {
            get {
                return ResourceManager.GetString("setting_appicon_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App icon.
        /// </summary>
        internal static string setting_appicon_title {
            get {
                return ResourceManager.GetString("setting_appicon_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app can be used in both light and dark mode. By default it will pick whatever the device is set to. If either theme is preferred a specific theme can be chosen here..
        /// </summary>
        internal static string setting_apptheme_description {
            get {
                return ResourceManager.GetString("setting_apptheme_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App theme.
        /// </summary>
        internal static string setting_apptheme_title {
            get {
                return ResourceManager.GetString("setting_apptheme_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If there&apos;s a valid URL on the clipboard while adding a contribution, the app will ask if metadata from that URL should be used to prefill the contribution..
        /// </summary>
        internal static string setting_contributionfromurl_description {
            get {
                return ResourceManager.GetString("setting_contributionfromurl_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create contribution from URL.
        /// </summary>
        internal static string setting_contributionfromurl_title {
            get {
                return ResourceManager.GetString("setting_contributionfromurl_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By default, we select the language that you&apos;re using on your device if translations for it are available. However, if you want to use this app in a different language you can override it here..
        /// </summary>
        internal static string setting_language_description {
            get {
                return ResourceManager.GetString("setting_language_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string setting_language_title {
            get {
                return ResourceManager.GetString("setting_language_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grabbing the contribution areas....
        /// </summary>
        internal static string splash_contributionareas {
            get {
                return ResourceManager.GetString("splash_contributionareas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syncing the contribution types....
        /// </summary>
        internal static string splash_contributiontypes {
            get {
                return ResourceManager.GetString("splash_contributiontypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting things ready....
        /// </summary>
        internal static string splash_gettingready {
            get {
                return ResourceManager.GetString("splash_gettingready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Putting visibilities in place....
        /// </summary>
        internal static string splash_visibilities {
            get {
                return ResourceManager.GetString("splash_visibilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        internal static string tabs_activities {
            get {
                return ResourceManager.GetString("tabs_activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badges.
        /// </summary>
        internal static string tabs_badges {
            get {
                return ResourceManager.GetString("tabs_badges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string tabs_settings {
            get {
                return ResourceManager.GetString("tabs_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string tabs_statistics {
            get {
                return ResourceManager.GetString("tabs_statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        internal static string theme_dark {
            get {
                return ResourceManager.GetString("theme_dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string theme_light {
            get {
                return ResourceManager.GetString("theme_light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Default.
        /// </summary>
        internal static string theme_systemdefault {
            get {
                return ResourceManager.GetString("theme_systemdefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App theme.
        /// </summary>
        internal static string themepicker_title {
            get {
                return ResourceManager.GetString("themepicker_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is a required field..
        /// </summary>
        internal static string validation_variablefield {
            get {
                return ResourceManager.GetString("validation_variablefield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View licenses.
        /// </summary>
        internal static string view_licenses {
            get {
                return ResourceManager.GetString("view_licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility.
        /// </summary>
        internal static string visibility_title {
            get {
                return ResourceManager.GetString("visibility_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This activity was recorded in the previous contribution window and therefore it cannot be edited or deleted..
        /// </summary>
        internal static string warning_description_activitylocked {
            get {
                return ResourceManager.GetString("warning_description_activitylocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold on....
        /// </summary>
        internal static string warning_title {
            get {
                return ResourceManager.GetString("warning_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity locked.
        /// </summary>
        internal static string warning_title_activitylocked {
            get {
                return ResourceManager.GetString("warning_title_activitylocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
