//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVP.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("MVP.Resources.Translations", typeof(Translations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string contributions_title {
            get {
                return ResourceManager.GetString("contributions_title", resourceCulture);
            }
        }
        
        internal static string search_placeholder {
            get {
                return ResourceManager.GetString("search_placeholder", resourceCulture);
            }
        }
        
        internal static string profile_title {
            get {
                return ResourceManager.GetString("profile_title", resourceCulture);
            }
        }
        
        internal static string setting_contributionfromurl_title {
            get {
                return ResourceManager.GetString("setting_contributionfromurl_title", resourceCulture);
            }
        }
        
        internal static string setting_contributionfromurl_description {
            get {
                return ResourceManager.GetString("setting_contributionfromurl_description", resourceCulture);
            }
        }
        
        internal static string setting_apptheme_title {
            get {
                return ResourceManager.GetString("setting_apptheme_title", resourceCulture);
            }
        }
        
        internal static string setting_apptheme_description {
            get {
                return ResourceManager.GetString("setting_apptheme_description", resourceCulture);
            }
        }
        
        internal static string button_logout {
            get {
                return ResourceManager.GetString("button_logout", resourceCulture);
            }
        }
        
        internal static string tabs_activities {
            get {
                return ResourceManager.GetString("tabs_activities", resourceCulture);
            }
        }
        
        internal static string tabs_statistics {
            get {
                return ResourceManager.GetString("tabs_statistics", resourceCulture);
            }
        }
        
        internal static string tabs_badges {
            get {
                return ResourceManager.GetString("tabs_badges", resourceCulture);
            }
        }
        
        internal static string tabs_settings {
            get {
                return ResourceManager.GetString("tabs_settings", resourceCulture);
            }
        }
        
        internal static string contributionform_title_add {
            get {
                return ResourceManager.GetString("contributionform_title_add", resourceCulture);
            }
        }
        
        internal static string contributionform_title_edit {
            get {
                return ResourceManager.GetString("contributionform_title_edit", resourceCulture);
            }
        }
        
        internal static string language_english {
            get {
                return ResourceManager.GetString("language_english", resourceCulture);
            }
        }
        
        internal static string language_dutch {
            get {
                return ResourceManager.GetString("language_dutch", resourceCulture);
            }
        }
        
        internal static string languagepicker_title {
            get {
                return ResourceManager.GetString("languagepicker_title", resourceCulture);
            }
        }
        
        internal static string contributiondetails_title {
            get {
                return ResourceManager.GetString("contributiondetails_title", resourceCulture);
            }
        }
        
        internal static string field_activity_type {
            get {
                return ResourceManager.GetString("field_activity_type", resourceCulture);
            }
        }
        
        internal static string field_url {
            get {
                return ResourceManager.GetString("field_url", resourceCulture);
            }
        }
        
        internal static string field_title {
            get {
                return ResourceManager.GetString("field_title", resourceCulture);
            }
        }
        
        internal static string field_primary_contribution_area {
            get {
                return ResourceManager.GetString("field_primary_contribution_area", resourceCulture);
            }
        }
        
        internal static string field_additional_contribution_areas {
            get {
                return ResourceManager.GetString("field_additional_contribution_areas", resourceCulture);
            }
        }
        
        internal static string field_activity_date {
            get {
                return ResourceManager.GetString("field_activity_date", resourceCulture);
            }
        }
        
        internal static string field_description {
            get {
                return ResourceManager.GetString("field_description", resourceCulture);
            }
        }
        
        internal static string field_visibility {
            get {
                return ResourceManager.GetString("field_visibility", resourceCulture);
            }
        }
        
        internal static string button_delete_contribution {
            get {
                return ResourceManager.GetString("button_delete_contribution", resourceCulture);
            }
        }
        
        internal static string about_title {
            get {
                return ResourceManager.GetString("about_title", resourceCulture);
            }
        }
        
        internal static string about_why_title {
            get {
                return ResourceManager.GetString("about_why_title", resourceCulture);
            }
        }
        
        internal static string about_why_description {
            get {
                return ResourceManager.GetString("about_why_description", resourceCulture);
            }
        }
        
        internal static string about_opensource_title {
            get {
                return ResourceManager.GetString("about_opensource_title", resourceCulture);
            }
        }
        
        internal static string about_opensource_description {
            get {
                return ResourceManager.GetString("about_opensource_description", resourceCulture);
            }
        }
        
        internal static string button_becomesponsor {
            get {
                return ResourceManager.GetString("button_becomesponsor", resourceCulture);
            }
        }
        
        internal static string contribution_form_timeframememo {
            get {
                return ResourceManager.GetString("contribution_form_timeframememo", resourceCulture);
            }
        }
        
        internal static string contributionform_activitytype_placeholder {
            get {
                return ResourceManager.GetString("contributionform_activitytype_placeholder", resourceCulture);
            }
        }
        
        internal static string contributionform_technologyarea_placeholder {
            get {
                return ResourceManager.GetString("contributionform_technologyarea_placeholder", resourceCulture);
            }
        }
        
        internal static string contributionform_additionaltechnologyarea_placeholder {
            get {
                return ResourceManager.GetString("contributionform_additionaltechnologyarea_placeholder", resourceCulture);
            }
        }
        
        internal static string contributionform_visibility_placeholder {
            get {
                return ResourceManager.GetString("contributionform_visibility_placeholder", resourceCulture);
            }
        }
        
        internal static string setting_language_title {
            get {
                return ResourceManager.GetString("setting_language_title", resourceCulture);
            }
        }
        
        internal static string setting_language_description {
            get {
                return ResourceManager.GetString("setting_language_description", resourceCulture);
            }
        }
        
        internal static string themepicker_title {
            get {
                return ResourceManager.GetString("themepicker_title", resourceCulture);
            }
        }
        
        internal static string contributiontypepicker_title {
            get {
                return ResourceManager.GetString("contributiontypepicker_title", resourceCulture);
            }
        }
        
        internal static string contributiontechnologypicker_title {
            get {
                return ResourceManager.GetString("contributiontechnologypicker_title", resourceCulture);
            }
        }
        
        internal static string splash_contributionareas {
            get {
                return ResourceManager.GetString("splash_contributionareas", resourceCulture);
            }
        }
        
        internal static string splash_contributiontypes {
            get {
                return ResourceManager.GetString("splash_contributiontypes", resourceCulture);
            }
        }
        
        internal static string splash_visibilities {
            get {
                return ResourceManager.GetString("splash_visibilities", resourceCulture);
            }
        }
        
        internal static string splash_gettingready {
            get {
                return ResourceManager.GetString("splash_gettingready", resourceCulture);
            }
        }
        
        internal static string theme_systemdefault {
            get {
                return ResourceManager.GetString("theme_systemdefault", resourceCulture);
            }
        }
        
        internal static string theme_light {
            get {
                return ResourceManager.GetString("theme_light", resourceCulture);
            }
        }
        
        internal static string theme_dark {
            get {
                return ResourceManager.GetString("theme_dark", resourceCulture);
            }
        }
        
        internal static string visibility_title {
            get {
                return ResourceManager.GetString("visibility_title", resourceCulture);
            }
        }
        
        internal static string icon_default {
            get {
                return ResourceManager.GetString("icon_default", resourceCulture);
            }
        }
        
        internal static string icon_darkblue {
            get {
                return ResourceManager.GetString("icon_darkblue", resourceCulture);
            }
        }
        
        internal static string icon_black {
            get {
                return ResourceManager.GetString("icon_black", resourceCulture);
            }
        }
        
        internal static string icon_white {
            get {
                return ResourceManager.GetString("icon_white", resourceCulture);
            }
        }
        
        internal static string icon_rainbow {
            get {
                return ResourceManager.GetString("icon_rainbow", resourceCulture);
            }
        }
        
        internal static string setting_appicon_title {
            get {
                return ResourceManager.GetString("setting_appicon_title", resourceCulture);
            }
        }
        
        internal static string setting_appicon_description {
            get {
                return ResourceManager.GetString("setting_appicon_description", resourceCulture);
            }
        }
        
        internal static string alert_yes {
            get {
                return ResourceManager.GetString("alert_yes", resourceCulture);
            }
        }
        
        internal static string alert_no {
            get {
                return ResourceManager.GetString("alert_no", resourceCulture);
            }
        }
        
        internal static string alert_ok {
            get {
                return ResourceManager.GetString("alert_ok", resourceCulture);
            }
        }
        
        internal static string alert_cancel {
            get {
                return ResourceManager.GetString("alert_cancel", resourceCulture);
            }
        }
        
        internal static string alert_error_title {
            get {
                return ResourceManager.GetString("alert_error_title", resourceCulture);
            }
        }
        
        internal static string alert_warning_title {
            get {
                return ResourceManager.GetString("alert_warning_title", resourceCulture);
            }
        }
        
        internal static string alert_contribution_deleteconfirmation {
            get {
                return ResourceManager.GetString("alert_contribution_deleteconfirmation", resourceCulture);
            }
        }
        
        internal static string alert_error_unexpected {
            get {
                return ResourceManager.GetString("alert_error_unexpected", resourceCulture);
            }
        }
        
        internal static string alert_error_badrequest {
            get {
                return ResourceManager.GetString("alert_error_badrequest", resourceCulture);
            }
        }
        
        internal static string alert_error_servererror {
            get {
                return ResourceManager.GetString("alert_error_servererror", resourceCulture);
            }
        }
        
        internal static string alert_error_unauthorized {
            get {
                return ResourceManager.GetString("alert_error_unauthorized", resourceCulture);
            }
        }
        
        internal static string clipboard_alert_title {
            get {
                return ResourceManager.GetString("clipboard_alert_title", resourceCulture);
            }
        }
        
        internal static string clipboard_alert_description {
            get {
                return ResourceManager.GetString("clipboard_alert_description", resourceCulture);
            }
        }
        
        internal static string alert_contribution_notdeleted {
            get {
                return ResourceManager.GetString("alert_contribution_notdeleted", resourceCulture);
            }
        }
        
        internal static string validation_variablefield {
            get {
                return ResourceManager.GetString("validation_variablefield", resourceCulture);
            }
        }
        
        internal static string warning_title_activitylocked {
            get {
                return ResourceManager.GetString("warning_title_activitylocked", resourceCulture);
            }
        }
        
        internal static string warning_description_activitylocked {
            get {
                return ResourceManager.GetString("warning_description_activitylocked", resourceCulture);
            }
        }
        
        internal static string additionaltechnologypicker_title {
            get {
                return ResourceManager.GetString("additionaltechnologypicker_title", resourceCulture);
            }
        }
        
        internal static string alert_error_nomvpaccount {
            get {
                return ResourceManager.GetString("alert_error_nomvpaccount", resourceCulture);
            }
        }
        
        internal static string progress_saving {
            get {
                return ResourceManager.GetString("progress_saving", resourceCulture);
            }
        }
        
        internal static string licenses_title {
            get {
                return ResourceManager.GetString("licenses_title", resourceCulture);
            }
        }
        
        internal static string about_licenses_title {
            get {
                return ResourceManager.GetString("about_licenses_title", resourceCulture);
            }
        }
        
        internal static string about_licenses_description {
            get {
                return ResourceManager.GetString("about_licenses_description", resourceCulture);
            }
        }
        
        internal static string button_viewlicenses {
            get {
                return ResourceManager.GetString("button_viewlicenses", resourceCulture);
            }
        }
        
        internal static string progress_loading_url_data {
            get {
                return ResourceManager.GetString("progress_loading_url_data", resourceCulture);
            }
        }
        
        internal static string contributionform_save {
            get {
                return ResourceManager.GetString("contributionform_save", resourceCulture);
            }
        }
        
        internal static string contributiondetails_edit {
            get {
                return ResourceManager.GetString("contributiondetails_edit", resourceCulture);
            }
        }
        
        internal static string error_title_validationfailed {
            get {
                return ResourceManager.GetString("error_title_validationfailed", resourceCulture);
            }
        }
        
        internal static string error_description_validationfailed {
            get {
                return ResourceManager.GetString("error_description_validationfailed", resourceCulture);
            }
        }
        
        internal static string empty_state_title {
            get {
                return ResourceManager.GetString("empty_state_title", resourceCulture);
            }
        }
        
        internal static string empty_state_contributions {
            get {
                return ResourceManager.GetString("empty_state_contributions", resourceCulture);
            }
        }
        
        internal static string contribution_add {
            get {
                return ResourceManager.GetString("contribution_add", resourceCulture);
            }
        }
        
        internal static string empty_state_contributiontypes {
            get {
                return ResourceManager.GetString("empty_state_contributiontypes", resourceCulture);
            }
        }
        
        internal static string empty_state_contributiontechnologies {
            get {
                return ResourceManager.GetString("empty_state_contributiontechnologies", resourceCulture);
            }
        }
        
        internal static string empty_state_noresultcontributiontechnologies {
            get {
                return ResourceManager.GetString("empty_state_noresultcontributiontechnologies", resourceCulture);
            }
        }
        
        internal static string empty_state_visibilities {
            get {
                return ResourceManager.GetString("empty_state_visibilities", resourceCulture);
            }
        }
        
        internal static string alert_error_offline {
            get {
                return ResourceManager.GetString("alert_error_offline", resourceCulture);
            }
        }
        
        internal static string alert_error_offlinetitle {
            get {
                return ResourceManager.GetString("alert_error_offlinetitle", resourceCulture);
            }
        }
        
        internal static string alert_error_logoutwhileoffline {
            get {
                return ResourceManager.GetString("alert_error_logoutwhileoffline", resourceCulture);
            }
        }
    }
}
