//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVP.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translations_nl {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translations_nl() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MVP.Resources.Translations.nl", typeof(Translations_nl).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zonder de onderstaande personen zou deze applicatie niet mogelijk zijn geweest. Daarom hebben zij een plekje verdiend in onderstaande lijst om hun bijdrage te vieren..
        /// </summary>
        internal static string about_credits_description {
            get {
                return ResourceManager.GetString("about_credits_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        internal static string about_credits_title {
            get {
                return ResourceManager.GetString("about_credits_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze applicatie zou niet mogelijk zijn zonder het geweldige werk van anderen. Als je wil weten wie dit zijn, bekijk dan de licenties van hun geweldige software..
        /// </summary>
        internal static string about_licenses_description {
            get {
                return ResourceManager.GetString("about_licenses_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenties.
        /// </summary>
        internal static string about_licenses_title {
            get {
                return ResourceManager.GetString("about_licenses_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze applicatie is volledig open source. Als je deze applicatie met plezier gebruikt, overweeg dan om GitHub sponsor te worden. Hiermee koop je mij een digitale kop koffie per maand ☕️.
        /// </summary>
        internal static string about_opensource_description {
            get {
                return ResourceManager.GetString("about_opensource_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open source.
        /// </summary>
        internal static string about_opensource_title {
            get {
                return ResourceManager.GetString("about_opensource_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over deze app.
        /// </summary>
        internal static string about_title {
            get {
                return ResourceManager.GetString("about_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is altijd al een behoefte geweest om Microsoft MVPs hun activiteiten op een makkelijkere manier te laten beheren. Het bestaande online portaal werk prima, maar soortgelijke functionaliteit in compacte vorm op je mobiele apparaat is pas echt cool. En daarom is dit project ontstaan!.
        /// </summary>
        internal static string about_why_description {
            get {
                return ResourceManager.GetString("about_why_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waarom is deze app gebouwd?.
        /// </summary>
        internal static string about_why_title {
            get {
                return ResourceManager.GetString("about_why_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tester.
        /// </summary>
        internal static string acknowledgementtype_tester {
            get {
                return ResourceManager.GetString("acknowledgementtype_tester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vertaler.
        /// </summary>
        internal static string acknowledgementtype_translator {
            get {
                return ResourceManager.GetString("acknowledgementtype_translator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additionele kennisgebieden.
        /// </summary>
        internal static string additionaltechnologypicker_title {
            get {
                return ResourceManager.GetString("additionaltechnologypicker_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logingegevens zijn verlopen en we konden deze niet verversen. Daarom ben je uitgelogd. Log opnieuw in om verder te gaan..
        /// </summary>
        internal static string alert_error_unauthorized {
            get {
                return ResourceManager.GetString("alert_error_unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wordt een sponsor.
        /// </summary>
        internal static string becomesponsor {
            get {
                return ResourceManager.GetString("becomesponsor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwijder activiteit.
        /// </summary>
        internal static string button_delete_contribution {
            get {
                return ResourceManager.GetString("button_delete_contribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuleren.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We zien dat er een URL op het klembord staat. Moet er een activiteit gemaakt worden op basis van deze URL?.
        /// </summary>
        internal static string clipboard_description {
            get {
                return ResourceManager.GetString("clipboard_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dat ziet er goed uit!.
        /// </summary>
        internal static string clipboard_title {
            get {
                return ResourceManager.GetString("clipboard_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toevoegen.
        /// </summary>
        internal static string contribution_add {
            get {
                return ResourceManager.GetString("contribution_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet je zeker dat je deze activiteit wil verwijderen? Dit kan niet ongedaan gemaakt worden..
        /// </summary>
        internal static string contributiondetail_deleteconfirmation {
            get {
                return ResourceManager.GetString("contributiondetail_deleteconfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activiteit kon niet verwijderd worden. Wellicht was deze al verwijderd of vond deze plaats in een voorgaande toekenningscyclus?.
        /// </summary>
        internal static string contributiondetail_notdeleted {
            get {
                return ResourceManager.GetString("contributiondetail_notdeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wijzigen.
        /// </summary>
        internal static string contributiondetails_edit {
            get {
                return ResourceManager.GetString("contributiondetails_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activiteitsdetails.
        /// </summary>
        internal static string contributiondetails_title {
            get {
                return ResourceManager.GetString("contributiondetails_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kies het activiteitstype dat het beste past bij deze activiteit..
        /// </summary>
        internal static string contributionform_activitytype_placeholder {
            get {
                return ResourceManager.GetString("contributionform_activitytype_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kies maximaal 2 additionele kennisgebieden die ook van toepassing zijn op deze activiteit..
        /// </summary>
        internal static string contributionform_additionaltechnologyarea_placeholder {
            get {
                return ResourceManager.GetString("contributionform_additionaltechnologyarea_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opslaan.
        /// </summary>
        internal static string contributionform_save {
            get {
                return ResourceManager.GetString("contributionform_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kies het kennisgebied dat de primaire focus van deze activiteit is..
        /// </summary>
        internal static string contributionform_technologyarea_placeholder {
            get {
                return ResourceManager.GetString("contributionform_technologyarea_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activiteiten voor de toekenningscyclus van juli moeten plaatsvinden tussen {0} en {1}. Activiteiten die zijn ingediend na {0} zullen voor een toekomstige cyclus worden overwogen..
        /// </summary>
        internal static string contributionform_timeframememo {
            get {
                return ResourceManager.GetString("contributionform_timeframememo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activiteit toevoegen.
        /// </summary>
        internal static string contributionform_title_add {
            get {
                return ResourceManager.GetString("contributionform_title_add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activiteit bewerken.
        /// </summary>
        internal static string contributionform_title_edit {
            get {
                return ResourceManager.GetString("contributionform_title_edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kies het zichtbaarheidsniveau van deze activiteit..
        /// </summary>
        internal static string contributionform_visibility_placeholder {
            get {
                return ResourceManager.GetString("contributionform_visibility_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activiteiten.
        /// </summary>
        internal static string contributions_title {
            get {
                return ResourceManager.GetString("contributions_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primaire kennisgebied.
        /// </summary>
        internal static string contributiontechnologypicker_title {
            get {
                return ResourceManager.GetString("contributiontechnologypicker_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activiteitstype.
        /// </summary>
        internal static string contributiontypepicker_title {
            get {
                return ResourceManager.GetString("contributiontypepicker_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen activiteiten gevonden. Voeg een nieuwe activiteit toe of ververs het overzicht om bestaande activiteiten op te halen..
        /// </summary>
        internal static string empty_state_contributions {
            get {
                return ResourceManager.GetString("empty_state_contributions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen kennisgebieden gevonden..
        /// </summary>
        internal static string empty_state_contributiontechnologies {
            get {
                return ResourceManager.GetString("empty_state_contributiontechnologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen activiteitstypes gevonden..
        /// </summary>
        internal static string empty_state_contributiontypes {
            get {
                return ResourceManager.GetString("empty_state_contributiontypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoekopdracht leverde geen resultaten op. Probeer een andere zoekopdracht..
        /// </summary>
        internal static string empty_state_noresultcontributiontechnologies {
            get {
                return ResourceManager.GetString("empty_state_noresultcontributiontechnologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooh...het is leeg hier!.
        /// </summary>
        internal static string empty_state_title {
            get {
                return ResourceManager.GetString("empty_state_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen zichtbaarheden gevonden..
        /// </summary>
        internal static string empty_state_visibilities {
            get {
                return ResourceManager.GetString("empty_state_visibilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verzoek kom niet verwerkt worden. Probeer het later opnieuw..
        /// </summary>
        internal static string error_badrequest {
            get {
                return ResourceManager.GetString("error_badrequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicatieicoon kon niet veranderd worden. Probeer het later opnieuw..
        /// </summary>
        internal static string error_couldntchangeicon {
            get {
                return ResourceManager.GetString("error_couldntchangeicon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taal kon niet veranderd worden. Probeer het later opnieuw..
        /// </summary>
        internal static string error_couldntchangelanguage {
            get {
                return ResourceManager.GetString("error_couldntchangelanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicatiethema kon niet veranderd worden. Probeer het later opnieuw..
        /// </summary>
        internal static string error_couldntchangetheme {
            get {
                return ResourceManager.GetString("error_couldntchangetheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activiteiten konden niet worden geladen. We weten niet precies waarom, maar er is een melding gemaakt. Probeer het later opnieuw..
        /// </summary>
        internal static string error_couldntloadmorecontributions {
            get {
                return ResourceManager.GetString("error_couldntloadmorecontributions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profielinformatie kon niet ververst worden. We weten niet precies waarom, maar er is een melding gemaakt. Probeer het later opnieuw..
        /// </summary>
        internal static string error_couldntrefreshprofile {
            get {
                return ResourceManager.GetString("error_couldntrefreshprofile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activiteit kon niet worden opgeslagen. We weten niet precies waarom, maar er is een melding gemaakt. Probeer het later opnieuw..
        /// </summary>
        internal static string error_couldntsavecontribution {
            get {
                return ResourceManager.GetString("error_couldntsavecontribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze gegevens konden niet worden geladen. We weten niet precies waarom, maar er is een melding gemaakt. Probeer het later opnieuw..
        /// </summary>
        internal static string error_data_not_loaded {
            get {
                return ResourceManager.GetString("error_data_not_loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niet alle verplichte velden zijn ingevuld. Vul deze in en probeer het opnieuw..
        /// </summary>
        internal static string error_description_validationfailed {
            get {
                return ResourceManager.GetString("error_description_validationfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is momenteel geen internetverbinding. Dit kan ervoor zorgen dat je niet opnieuw kunt inloggen. Weet je zeker dat je verder wil gaan?.
        /// </summary>
        internal static string error_logoutwhileoffline {
            get {
                return ResourceManager.GetString("error_logoutwhileoffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We konden je niet authenticeren met de aangeleverde gegevens. Weet je zeker dat je het account gebruikt dat geassocieerd is met je MVP ID?.
        /// </summary>
        internal static string error_nomvpaccount {
            get {
                return ResourceManager.GetString("error_nomvpaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dit verzoek kan niet uitgevoerd worden zonder internetverbinding. Probeer het later opnieuw..
        /// </summary>
        internal static string error_offline {
            get {
                return ResourceManager.GetString("error_offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen internetverbinding.
        /// </summary>
        internal static string error_offline_title {
            get {
                return ResourceManager.GetString("error_offline_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verzoek kon niet verwerkt worden. Probeer het later opnieuw..
        /// </summary>
        internal static string error_servererror {
            get {
                return ResourceManager.GetString("error_servererror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er ging iets mis.
        /// </summary>
        internal static string error_title {
            get {
                return ResourceManager.GetString("error_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validatie mislukt.
        /// </summary>
        internal static string error_title_validationfailed {
            get {
                return ResourceManager.GetString("error_title_validationfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er ging iets mis. Er is een melding gemaakt en we zullen dit zo snel mogelijk onderzoeken..
        /// </summary>
        internal static string error_unexpected {
            get {
                return ResourceManager.GetString("error_unexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activiteitsdatum.
        /// </summary>
        internal static string field_activity_date {
            get {
                return ResourceManager.GetString("field_activity_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activiteitstype.
        /// </summary>
        internal static string field_activity_type {
            get {
                return ResourceManager.GetString("field_activity_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additionele kennisgebieden.
        /// </summary>
        internal static string field_additional_contribution_areas {
            get {
                return ResourceManager.GetString("field_additional_contribution_areas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaarlijkse hoeveelheid.
        /// </summary>
        internal static string field_annual_quantity {
            get {
                return ResourceManager.GetString("field_annual_quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaarlijkse bereik.
        /// </summary>
        internal static string field_annual_reach {
            get {
                return ResourceManager.GetString("field_annual_reach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaarlijkse unieke bezoekers.
        /// </summary>
        internal static string field_annual_unique_visitors {
            get {
                return ResourceManager.GetString("field_annual_unique_visitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aanwezigen bij sessies.
        /// </summary>
        internal static string field_attendees_of_talks {
            get {
                return ResourceManager.GetString("field_attendees_of_talks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activiteiten.
        /// </summary>
        internal static string field_contributions {
            get {
                return ResourceManager.GetString("field_contributions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verkochte exemplaren.
        /// </summary>
        internal static string field_copies_sold {
            get {
                return ResourceManager.GetString("field_copies_sold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omschrijving.
        /// </summary>
        internal static string field_description {
            get {
                return ResourceManager.GetString("field_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meetings.
        /// </summary>
        internal static string field_meetings {
            get {
                return ResourceManager.GetString("field_meetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leden.
        /// </summary>
        internal static string field_members {
            get {
                return ResourceManager.GetString("field_members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal antwoorden.
        /// </summary>
        internal static string field_number_of_answers {
            get {
                return ResourceManager.GetString("field_number_of_answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal artikelen.
        /// </summary>
        internal static string field_number_of_articles {
            get {
                return ResourceManager.GetString("field_number_of_articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal aanwezigen.
        /// </summary>
        internal static string field_number_of_attendees {
            get {
                return ResourceManager.GetString("field_number_of_attendees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal boeken.
        /// </summary>
        internal static string field_number_of_books {
            get {
                return ResourceManager.GetString("field_number_of_books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal conferenties.
        /// </summary>
        internal static string field_number_of_conferences {
            get {
                return ResourceManager.GetString("field_number_of_conferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal downloads.
        /// </summary>
        internal static string field_number_of_downloads {
            get {
                return ResourceManager.GetString("field_number_of_downloads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal evenementen.
        /// </summary>
        internal static string field_number_of_events {
            get {
                return ResourceManager.GetString("field_number_of_events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal evenementdeelnames.
        /// </summary>
        internal static string field_number_of_events_participated {
            get {
                return ResourceManager.GetString("field_number_of_events_participated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal gegeven feedback.
        /// </summary>
        internal static string field_number_of_feedbacks_provided {
            get {
                return ResourceManager.GetString("field_number_of_feedbacks_provided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal volgers.
        /// </summary>
        internal static string field_number_of_followers {
            get {
                return ResourceManager.GetString("field_number_of_followers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal mentees.
        /// </summary>
        internal static string field_number_of_mentees {
            get {
                return ResourceManager.GetString("field_number_of_mentees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal mentorschap activiteiten.
        /// </summary>
        internal static string field_number_of_mentorship_activity {
            get {
                return ResourceManager.GetString("field_number_of_mentorship_activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal berichten.
        /// </summary>
        internal static string field_number_of_posts {
            get {
                return ResourceManager.GetString("field_number_of_posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal projecten.
        /// </summary>
        internal static string field_number_of_projects {
            get {
                return ResourceManager.GetString("field_number_of_projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal voorbeelden.
        /// </summary>
        internal static string field_number_of_samples {
            get {
                return ResourceManager.GetString("field_number_of_samples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal sites.
        /// </summary>
        internal static string field_number_of_sites {
            get {
                return ResourceManager.GetString("field_number_of_sites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal abonnees.
        /// </summary>
        internal static string field_number_of_subscribers {
            get {
                return ResourceManager.GetString("field_number_of_subscribers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal sessies.
        /// </summary>
        internal static string field_number_of_talks {
            get {
                return ResourceManager.GetString("field_number_of_talks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal gemodereerde threads.
        /// </summary>
        internal static string field_number_of_threads_moderated {
            get {
                return ResourceManager.GetString("field_number_of_threads_moderated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal videos.
        /// </summary>
        internal static string field_number_of_videos {
            get {
                return ResourceManager.GetString("field_number_of_videos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal weergaves.
        /// </summary>
        internal static string field_number_of_views {
            get {
                return ResourceManager.GetString("field_number_of_views", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal bezoekers.
        /// </summary>
        internal static string field_number_of_visitors {
            get {
                return ResourceManager.GetString("field_number_of_visitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primaire kennisgebied.
        /// </summary>
        internal static string field_primary_contribution_area {
            get {
                return ResourceManager.GetString("field_primary_contribution_area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project(en).
        /// </summary>
        internal static string field_projects {
            get {
                return ResourceManager.GetString("field_projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull Requests/Issues/Submissions.
        /// </summary>
        internal static string field_prs_issues_submissions {
            get {
                return ResourceManager.GetString("field_prs_issues_submissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel van activiteit.
        /// </summary>
        internal static string field_title {
            get {
                return ResourceManager.GetString("field_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string field_url {
            get {
                return ResourceManager.GetString("field_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal antwoordweergaces.
        /// </summary>
        internal static string field_views_of_answers {
            get {
                return ResourceManager.GetString("field_views_of_answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zichtbaarheid.
        /// </summary>
        internal static string field_visibility {
            get {
                return ResourceManager.GetString("field_visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zwart.
        /// </summary>
        internal static string icon_black {
            get {
                return ResourceManager.GetString("icon_black", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donkerblauw.
        /// </summary>
        internal static string icon_darkblue {
            get {
                return ResourceManager.GetString("icon_darkblue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standaard.
        /// </summary>
        internal static string icon_default {
            get {
                return ResourceManager.GetString("icon_default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regenboog.
        /// </summary>
        internal static string icon_rainbow {
            get {
                return ResourceManager.GetString("icon_rainbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wit.
        /// </summary>
        internal static string icon_white {
            get {
                return ResourceManager.GetString("icon_white", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nederlands.
        /// </summary>
        internal static string language_dutch {
            get {
                return ResourceManager.GetString("language_dutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engels.
        /// </summary>
        internal static string language_english {
            get {
                return ResourceManager.GetString("language_english", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        internal static string language_spanish {
            get {
                return ResourceManager.GetString("language_spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taal.
        /// </summary>
        internal static string languagepicker_title {
            get {
                return ResourceManager.GetString("languagepicker_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenties.
        /// </summary>
        internal static string licenses_title {
            get {
                return ResourceManager.GetString("licenses_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uitloggen.
        /// </summary>
        internal static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nee.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is momenteel geen internetverbinding. Hierdoor kunnen activiteiten niet geladen worden. Probeer het later opnieuw..
        /// </summary>
        internal static string offline_contributions {
            get {
                return ResourceManager.GetString("offline_contributions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beheer al je activiteiten vanuit je broekzak..
        /// </summary>
        internal static string onboarding_1_description {
            get {
                return ResourceManager.GetString("onboarding_1_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simpel en effectief.
        /// </summary>
        internal static string onboarding_1_title {
            get {
                return ResourceManager.GetString("onboarding_1_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voeg direct activiteiten toe op basis van een URL op je klembord. Wij zorgen ervoor dat we zoveel mogelijk invullen zodat je snel verder kan met toevoegen..
        /// </summary>
        internal static string onboarding_3_description {
            get {
                return ResourceManager.GetString("onboarding_3_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Snel toevoegen.
        /// </summary>
        internal static string onboarding_3_title {
            get {
                return ResourceManager.GetString("onboarding_3_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instellingen.
        /// </summary>
        internal static string profile_title {
            get {
                return ResourceManager.GetString("profile_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezig met URL metadata ophalen....
        /// </summary>
        internal static string progress_loading_url_data {
            get {
                return ResourceManager.GetString("progress_loading_url_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezig met opslaan....
        /// </summary>
        internal static string progress_saving {
            get {
                return ResourceManager.GetString("progress_saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoeken....
        /// </summary>
        internal static string search_placeholder {
            get {
                return ResourceManager.GetString("search_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vind je het standaardicoon niet mooi? Er zijn een aantal alternatieve opties beschikbaar..
        /// </summary>
        internal static string setting_appicon_description {
            get {
                return ResourceManager.GetString("setting_appicon_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icoon.
        /// </summary>
        internal static string setting_appicon_title {
            get {
                return ResourceManager.GetString("setting_appicon_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze applicatie kan zowel in een lichte als een donkere weergave gebruikt worden. Standaard neemt de applicatie de instelling van het apparaat over. Wanneer een van beide weergaves de voorkeur heeft kan deze hier ingesteld worden..
        /// </summary>
        internal static string setting_apptheme_description {
            get {
                return ResourceManager.GetString("setting_apptheme_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weergave.
        /// </summary>
        internal static string setting_apptheme_title {
            get {
                return ResourceManager.GetString("setting_apptheme_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wanneer er zich een geldige URL op het klembord bevindt zodra een activiteit wordt toegevoegd, zal de app vragen of de metadata van deze URL gebruikt moet worden om de activiteit deels automatisch in te vullen..
        /// </summary>
        internal static string setting_contributionfromurl_description {
            get {
                return ResourceManager.GetString("setting_contributionfromurl_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activiteit maken via klembord.
        /// </summary>
        internal static string setting_contributionfromurl_title {
            get {
                return ResourceManager.GetString("setting_contributionfromurl_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standaard selecteren we de taal die je op jouw apparaat gebruikt, mits hier vertalingen beschikbaar voor zijn. Wanneer je deze applicatie in een andere taal wil gebruiken kun je dat hier aanpassen..
        /// </summary>
        internal static string setting_language_description {
            get {
                return ResourceManager.GetString("setting_language_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taal.
        /// </summary>
        internal static string setting_language_title {
            get {
                return ResourceManager.GetString("setting_language_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kennisgebieden bijeenharken....
        /// </summary>
        internal static string splash_contributionareas {
            get {
                return ResourceManager.GetString("splash_contributionareas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activiteitstypes synchroniseren....
        /// </summary>
        internal static string splash_contributiontypes {
            get {
                return ResourceManager.GetString("splash_contributiontypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bezig om alles klaar te zetten....
        /// </summary>
        internal static string splash_gettingready {
            get {
                return ResourceManager.GetString("splash_gettingready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zichtbaarheden visualiseren....
        /// </summary>
        internal static string splash_visibilities {
            get {
                return ResourceManager.GetString("splash_visibilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activiteiten.
        /// </summary>
        internal static string tabs_activities {
            get {
                return ResourceManager.GetString("tabs_activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Badges.
        /// </summary>
        internal static string tabs_badges {
            get {
                return ResourceManager.GetString("tabs_badges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instellingen.
        /// </summary>
        internal static string tabs_settings {
            get {
                return ResourceManager.GetString("tabs_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistieken.
        /// </summary>
        internal static string tabs_statistics {
            get {
                return ResourceManager.GetString("tabs_statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donker.
        /// </summary>
        internal static string theme_dark {
            get {
                return ResourceManager.GetString("theme_dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licht.
        /// </summary>
        internal static string theme_light {
            get {
                return ResourceManager.GetString("theme_light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standaardwaarde van apparaat.
        /// </summary>
        internal static string theme_systemdefault {
            get {
                return ResourceManager.GetString("theme_systemdefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicatiethema.
        /// </summary>
        internal static string themepicker_title {
            get {
                return ResourceManager.GetString("themepicker_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is een verplicht veld..
        /// </summary>
        internal static string validation_variablefield {
            get {
                return ResourceManager.GetString("validation_variablefield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bekijk licenties.
        /// </summary>
        internal static string view_licenses {
            get {
                return ResourceManager.GetString("view_licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zichtbaarheid.
        /// </summary>
        internal static string visibility_title {
            get {
                return ResourceManager.GetString("visibility_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze activiteit is geregistreerd in de voorgaande toekenningscyclus en kan daarom niet meer bewerkt of verwijderd worden..
        /// </summary>
        internal static string warning_description_activitylocked {
            get {
                return ResourceManager.GetString("warning_description_activitylocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wacht even....
        /// </summary>
        internal static string warning_title {
            get {
                return ResourceManager.GetString("warning_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activiteit gesloten.
        /// </summary>
        internal static string warning_title_activitylocked {
            get {
                return ResourceManager.GetString("warning_title_activitylocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
