// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

using System.Collections.Generic;
using Newtonsoft.Json;

namespace MVP.Models
{
    public partial class ContributionList
    {
        public IList<Contribution> Contributions { get; set; }
        public int? TotalContributions { get; set; }
        public int? PagingIndex { get; set; }
    }
}
